// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: BOX_REMOTE_CONTROL

#include "../ui.h"

void ui_mainScreen_screen_init(void)
{
    ui_mainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_mainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainScreen, lv_color_hex(0xE5F3FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GamePadPanel = lv_obj_create(ui_mainScreen);
    lv_obj_set_width(ui_GamePadPanel, 120);
    lv_obj_set_height(ui_GamePadPanel, 95);
    lv_obj_set_x(ui_GamePadPanel, 75);
    lv_obj_set_y(ui_GamePadPanel, -40);
    lv_obj_set_align(ui_GamePadPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GamePadPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GamePadPanel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GamePadPanel, lv_color_hex(0xE5F3FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GamePadPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GamePadPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GamePadPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GamePadPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_GamePadPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gamePadBtn = lv_btn_create(ui_GamePadPanel);
    lv_obj_set_width(ui_gamePadBtn, 70);
    lv_obj_set_height(ui_gamePadBtn, 70);
    lv_obj_set_x(ui_gamePadBtn, 0);
    lv_obj_set_y(ui_gamePadBtn, -10);
    lv_obj_set_align(ui_gamePadBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gamePadBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_gamePadBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_gamePadBtn, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gamePadBtn, lv_color_hex(0xE5F3FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gamePadBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_gamePadBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_gamePadBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_gamePadBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_gamePadBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_gamePadBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_gamePadBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gamePadBtnImage = lv_img_create(ui_gamePadBtn);
    lv_img_set_src(ui_gamePadBtnImage, &ui_img_game_pad_app_png);
    lv_obj_set_width(ui_gamePadBtnImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gamePadBtnImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gamePadBtnImage, 3);
    lv_obj_set_y(ui_gamePadBtnImage, 3);
    lv_obj_set_align(ui_gamePadBtnImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gamePadBtnImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_gamePadBtnImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gamePadLab = lv_label_create(ui_GamePadPanel);
    lv_obj_set_width(ui_gamePadLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gamePadLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gamePadLab, -3);
    lv_obj_set_y(ui_gamePadLab, 35);
    lv_obj_set_align(ui_gamePadLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gamePadLab, "GamePad");
    lv_obj_set_style_text_color(ui_gamePadLab, lv_color_hex(0x38393A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gamePadLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gamePadLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nesPanel = lv_obj_create(ui_mainScreen);
    lv_obj_set_width(ui_nesPanel, 120);
    lv_obj_set_height(ui_nesPanel, 95);
    lv_obj_set_x(ui_nesPanel, 75);
    lv_obj_set_y(ui_nesPanel, 60);
    lv_obj_set_align(ui_nesPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_nesPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_nesPanel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_nesPanel, lv_color_hex(0xE5F3FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nesPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_nesPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_nesPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_nesPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_nesPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NesBtn = lv_btn_create(ui_nesPanel);
    lv_obj_set_width(ui_NesBtn, 70);
    lv_obj_set_height(ui_NesBtn, 70);
    lv_obj_set_x(ui_NesBtn, 0);
    lv_obj_set_y(ui_NesBtn, -10);
    lv_obj_set_align(ui_NesBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NesBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NesBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NesBtn, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NesBtn, lv_color_hex(0xE5F3FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NesBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_NesBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_NesBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_NesBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_NesBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_NesBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_NesBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NesBtnImage = lv_img_create(ui_NesBtn);
    lv_img_set_src(ui_NesBtnImage, &ui_img_nes_app_png);
    lv_obj_set_width(ui_NesBtnImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NesBtnImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NesBtnImage, 3);
    lv_obj_set_y(ui_NesBtnImage, 3);
    lv_obj_set_align(ui_NesBtnImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NesBtnImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NesBtnImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NesLab = lv_label_create(ui_nesPanel);
    lv_obj_set_width(ui_NesLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NesLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NesLab, -3);
    lv_obj_set_y(ui_NesLab, 35);
    lv_obj_set_align(ui_NesLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NesLab, "NES emulator");
    lv_obj_set_style_text_color(ui_NesLab, lv_color_hex(0x38393A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NesLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NesLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rcPanel = lv_obj_create(ui_mainScreen);
    lv_obj_set_width(ui_rcPanel, 152);
    lv_obj_set_height(ui_rcPanel, 95);
    lv_obj_set_x(ui_rcPanel, -75);
    lv_obj_set_y(ui_rcPanel, 60);
    lv_obj_set_align(ui_rcPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rcPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rcPanel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rcPanel, lv_color_hex(0xE5F3FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rcPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rcPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rcPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rcPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rcPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RemoteBtn = lv_btn_create(ui_rcPanel);
    lv_obj_set_width(ui_RemoteBtn, 70);
    lv_obj_set_height(ui_RemoteBtn, 70);
    lv_obj_set_x(ui_RemoteBtn, 0);
    lv_obj_set_y(ui_RemoteBtn, -10);
    lv_obj_set_align(ui_RemoteBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RemoteBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RemoteBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RemoteBtn, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RemoteBtn, lv_color_hex(0xE5F3FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RemoteBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_RemoteBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_RemoteBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RemoteBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RemoteBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_RemoteBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_RemoteBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RemoteBtnImage = lv_img_create(ui_RemoteBtn);
    lv_img_set_src(ui_RemoteBtnImage, &ui_img_rc_app_png);
    lv_obj_set_width(ui_RemoteBtnImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RemoteBtnImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RemoteBtnImage, 3);
    lv_obj_set_y(ui_RemoteBtnImage, 3);
    lv_obj_set_align(ui_RemoteBtnImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RemoteBtnImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RemoteBtnImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RemoteBtnImage, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RemoteLab = lv_label_create(ui_rcPanel);
    lv_obj_set_width(ui_RemoteLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RemoteLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RemoteLab, -3);
    lv_obj_set_y(ui_RemoteLab, 35);
    lv_obj_set_align(ui_RemoteLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RemoteLab, "Remote Controller");
    lv_obj_set_style_text_color(ui_RemoteLab, lv_color_hex(0x38393A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RemoteLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RemoteLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingPanel = lv_obj_create(ui_mainScreen);
    lv_obj_set_width(ui_SettingPanel, 120);
    lv_obj_set_height(ui_SettingPanel, 95);
    lv_obj_set_x(ui_SettingPanel, -75);
    lv_obj_set_y(ui_SettingPanel, -40);
    lv_obj_set_align(ui_SettingPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingPanel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SettingPanel, lv_color_hex(0xE5F3FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SettingPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SettingPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SettingPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingBtn = lv_btn_create(ui_SettingPanel);
    lv_obj_set_width(ui_SettingBtn, 70);
    lv_obj_set_height(ui_SettingBtn, 70);
    lv_obj_set_x(ui_SettingBtn, 0);
    lv_obj_set_y(ui_SettingBtn, -10);
    lv_obj_set_align(ui_SettingBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingBtn, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SettingBtn, lv_color_hex(0xE5F3FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingBtn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SettingBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SettingBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SettingBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SettingBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SettingBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SettingBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingBtnImage = lv_img_create(ui_SettingBtn);
    lv_img_set_src(ui_SettingBtnImage, &ui_img_setting_app_png);
    lv_obj_set_width(ui_SettingBtnImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingBtnImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingBtnImage, 3);
    lv_obj_set_y(ui_SettingBtnImage, 3);
    lv_obj_set_align(ui_SettingBtnImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingBtnImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingBtnImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingLab = lv_label_create(ui_SettingPanel);
    lv_obj_set_width(ui_SettingLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingLab, -3);
    lv_obj_set_y(ui_SettingLab, 35);
    lv_obj_set_align(ui_SettingLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingLab, "Settings");
    lv_obj_set_style_text_color(ui_SettingLab, lv_color_hex(0x38393A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreenStatePanel = lv_obj_create(ui_mainScreen);
    lv_obj_set_width(ui_MainScreenStatePanel, 320);
    lv_obj_set_height(ui_MainScreenStatePanel, 25);
    lv_obj_clear_flag(ui_MainScreenStatePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainScreenStatePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainScreenStatePanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreenStatePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainScreenStatePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainScreenStatePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainScreenStatePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_MainScreenStatePanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel = lv_label_create(ui_MainScreenStatePanel);
    lv_obj_set_width(ui_TimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TimeLabel, "12 : 00");
    lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bluetoothImage = lv_img_create(ui_MainScreenStatePanel);
    lv_img_set_src(ui_bluetoothImage, &ui_img_ble_icon_20px_png);
    lv_obj_set_width(ui_bluetoothImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bluetoothImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bluetoothImage, -106);
    lv_obj_set_y(ui_bluetoothImage, 0);
    lv_obj_set_align(ui_bluetoothImage, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_bluetoothImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bluetoothImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiImage = lv_img_create(ui_MainScreenStatePanel);
    lv_img_set_src(ui_WifiImage, &ui_img_wifi_icon_18px_png);
    lv_obj_set_width(ui_WifiImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiImage, -86);
    lv_obj_set_y(ui_WifiImage, 0);
    lv_obj_set_align(ui_WifiImage, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_WifiImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_usbImage = lv_img_create(ui_MainScreenStatePanel);
    lv_img_set_src(ui_usbImage, &ui_img_usb_icon_20px_png);
    lv_obj_set_width(ui_usbImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_usbImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_usbImage, -63);
    lv_obj_set_y(ui_usbImage, 0);
    lv_obj_set_align(ui_usbImage, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_usbImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_usbImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_powerBar = lv_bar_create(ui_MainScreenStatePanel);
    lv_bar_set_value(ui_powerBar, 60, LV_ANIM_OFF);
    lv_obj_set_width(ui_powerBar, 30);
    lv_obj_set_height(ui_powerBar, 13);
    lv_obj_set_x(ui_powerBar, -28);
    lv_obj_set_y(ui_powerBar, 0);
    lv_obj_set_align(ui_powerBar, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_radius(ui_powerBar, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_powerBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_powerBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_powerBar, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_powerBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_powerBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_powerBar, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_powerBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_powerBar, lv_color_hex(0x292929), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_powerBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_powerLab = lv_label_create(ui_MainScreenStatePanel);
    lv_obj_set_width(ui_powerLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powerLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_powerLab, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_powerLab, "60%");
    lv_obj_set_style_text_color(ui_powerLab, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_powerLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_powerLab, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_MainScreenStatePanel);
    lv_obj_set_width(ui_Panel1, 2);
    lv_obj_set_height(ui_Panel1, 5);
    lv_obj_set_x(ui_Panel1, -26);
    lv_obj_set_y(ui_Panel1, 0);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_gamePadBtn, ui_event_gamePadBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NesBtn, ui_event_NesBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RemoteBtn, ui_event_RemoteBtn, LV_EVENT_ALL, NULL);

}
