// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: BOX_REMOTE_CONTROL

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void topCtrlDown_Animation(lv_obj_t *TargetObject, int delay);
void topCtrlUp_Animation(lv_obj_t *TargetObject, int delay);

// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
lv_obj_t *ui_mainScreen;
lv_obj_t *ui_GamePadPanel;
void ui_event_gamePadBtn(lv_event_t *e);
lv_obj_t *ui_gamePadBtn;
lv_obj_t *ui_gamePadBtnImage;
lv_obj_t *ui_gamePadLab;
lv_obj_t *ui_nesPanel;
void ui_event_NesBtn(lv_event_t *e);
lv_obj_t *ui_NesBtn;
lv_obj_t *ui_NesBtnImage;
lv_obj_t *ui_NesLab;
lv_obj_t *ui_rcPanel;
void ui_event_RemoteBtn(lv_event_t *e);
lv_obj_t *ui_RemoteBtn;
lv_obj_t *ui_RemoteBtnImage;
lv_obj_t *ui_RemoteLab;
lv_obj_t *ui_SettingPanel;
lv_obj_t *ui_SettingBtn;
lv_obj_t *ui_SettingBtnImage;
lv_obj_t *ui_SettingLab;
lv_obj_t *ui_MainScreenStatePanel;
lv_obj_t *ui_TimeLabel;
lv_obj_t *ui_bluetoothImage;
lv_obj_t *ui_WifiImage;
lv_obj_t *ui_usbImage;
lv_obj_t *ui_powerBar;
lv_obj_t *ui_powerLab;
lv_obj_t *ui_Panel1;

// SCREEN: ui_GamePadAppScreen
void ui_GamePadAppScreen_screen_init(void);
lv_obj_t *ui_GamePadAppScreen;
lv_obj_t *ui_GameTopPanel;
void ui_event_returnBtnInGamePad(lv_event_t *e);
lv_obj_t *ui_returnBtnInGamePad;
lv_obj_t *ui_returnBtnInGamePadIcon;
lv_obj_t *ui_returnLabInGamePad;
lv_obj_t *ui_gameScreenTitle;
void ui_event_GamePadTipsBtn(lv_event_t *e);
lv_obj_t *ui_GamePadTipsBtn;
lv_obj_t *ui_GamePadTipsBtnIcon;
lv_obj_t *ui_upBtn;
lv_obj_t *ui_upBtnIcon;
lv_obj_t *ui_leftBtn;
lv_obj_t *ui_leftBtnIcon;
lv_obj_t *ui_rightBtn;
lv_obj_t *ui_rightBtnIcon;
lv_obj_t *ui_downBtn;
lv_obj_t *ui_downBtnIcon;
lv_obj_t *ui_yBtn;
lv_obj_t *ui_xKeyLab;
lv_obj_t *ui_bBtn;
lv_obj_t *ui_bKeyLab;
lv_obj_t *ui_aBtn;
lv_obj_t *ui_aKeyLab;
lv_obj_t *ui_xBtn;
lv_obj_t *ui_yKeyLab;
lv_obj_t *ui_lbBtn;
lv_obj_t *ui_lbBtnLab;
lv_obj_t *ui_ltBtn;
lv_obj_t *ui_ltBtnLab;
lv_obj_t *ui_rbBtn;
lv_obj_t *ui_rbBtnLab;
lv_obj_t *ui_rtBtn;
lv_obj_t *ui_rtBtnLab;
lv_obj_t *ui_leftRocker;
lv_obj_t *ui_leftRockerBtn;
lv_obj_t *ui_rightRocker;
lv_obj_t *ui_rightRockerBtn;
lv_obj_t *ui_selectBtn;
lv_obj_t *ui_selectBtnLab;
lv_obj_t *ui_startBtn;
lv_obj_t *ui_startBtnLab;
lv_obj_t *ui_GamePadStatePanel;
lv_obj_t *ui_TimeLabel1;
lv_obj_t *ui_bluetoothImage1;
lv_obj_t *ui_WifiImage1;
lv_obj_t *ui_usbImage1;
lv_obj_t *ui_powerBar1;
lv_obj_t *ui_powerLab1;

// SCREEN: ui_RcAppScreen
void ui_RcAppScreen_screen_init(void);
lv_obj_t *ui_RcAppScreen;
lv_obj_t *ui_EspDroneStatePanel;
lv_obj_t *ui_TimeLabel2;
lv_obj_t *ui_bluetoothImage2;
lv_obj_t *ui_WifiImage2;
lv_obj_t *ui_usbImage2;
lv_obj_t *ui_powerBar2;
lv_obj_t *ui_powerLab2;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_dLeftRockerPanel;
lv_obj_t *ui_dLeftRockerBtn;
lv_obj_t *ui_dRightRockerPanel;
lv_obj_t *ui_dRightRockerBtn;
void ui_event_bindBtn(lv_event_t *e);
lv_obj_t *ui_bindBtn;
lv_obj_t *ui_RcTopPanel;
void ui_event_returnBtnInEspDrone(lv_event_t *e);
lv_obj_t *ui_returnBtnInEspDrone;
lv_obj_t *ui_returnBtnInEspDroneIcon;
lv_obj_t *ui_returnLabInEspDrone;
lv_obj_t *ui_espDroneTitle;
lv_obj_t *ui_RcDataPanel;
lv_obj_t *ui_dPLabel;
lv_obj_t *ui_dRLabel;
lv_obj_t *ui_dTLabel;
lv_obj_t *ui_dYLabel;
lv_obj_t *ui_dPLabelData;
lv_obj_t *ui_dRLabelData;
lv_obj_t *ui_dTLabelData;
lv_obj_t *ui_dYLabelData;

// SCREEN: ui_GamePadAppSettingScreen
void ui_GamePadAppSettingScreen_screen_init(void);
lv_obj_t *ui_GamePadAppSettingScreen;
lv_obj_t *ui_hidModeSelectPanel;
lv_obj_t *ui_hidSelectLab;
void ui_event_hidModeSelectBtn(lv_event_t *e);
lv_obj_t *ui_hidModeSelectBtn;
lv_obj_t *ui_hidModeSelectBtnPart;
lv_obj_t *ui_hidModeSelectLab;
lv_obj_t *ui_GameSettingTopPanel;
void ui_event_gamePadSettingCloseBtn(lv_event_t *e);
lv_obj_t *ui_gamePadSettingCloseBtn;
lv_obj_t *ui_gamePadSettingCloseBtnIcon;
lv_obj_t *ui_GamePadSettingLabel;
lv_obj_t *ui_GameModeSettingStatePanel;
lv_obj_t *ui_TimeLabel3;
lv_obj_t *ui_bluetoothImage3;
lv_obj_t *ui_WifiImage3;
lv_obj_t *ui_usbImage3;
lv_obj_t *ui_powerBar3;
lv_obj_t *ui_powerLab3;
lv_obj_t *ui_Panel5;
lv_obj_t *ui_RockerCalibrationPanel;
lv_obj_t *ui_rockerCalibrationLab;
void ui_event_rockerCalibrationStartBtn(lv_event_t *e);
lv_obj_t *ui_rockerCalibrationStartBtn;
lv_obj_t *ui_rockerCalibrationStartBtnText;
lv_obj_t *ui_VibrationFeedbackPanel;
lv_obj_t *ui_VibrationFeedbackLab;
void ui_event_VibrationFeedbackBtn(lv_event_t *e);
lv_obj_t *ui_VibrationFeedbackBtn;
lv_obj_t *ui_VibrationFeedbackBtnPart;
lv_obj_t *ui_VibrationFeedbackStateLab;
lv_obj_t *ui_RockerCalibrationSettingPanel;
lv_obj_t *ui_rockerCalibrationTipsLab;
lv_obj_t *ui_leftRockerCalibrate;
lv_obj_t *ui_leftRockerCalibrateBtn;
lv_obj_t *ui_rightRockerCalibrate;
lv_obj_t *ui_rightRockerCalibrateBtn;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_ble_[1] = {&ui_img_ble_28_png};
const lv_img_dsc_t *ui_imgset_brilliance_[1] = {&ui_img_brilliance_28_png};
const lv_img_dsc_t *ui_imgset_usb_[1] = {&ui_img_usb_28_png};
const lv_img_dsc_t *ui_imgset_vibration_[1] = {&ui_img_vibration_28_png};
const lv_img_dsc_t *ui_imgset_volume_ctrl_[1] = {&ui_img_volume_ctrl_26_png};
const lv_img_dsc_t *ui_imgset_wifi_[1] = {&ui_img_wifi_28_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
#error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void topCtrlDown_Animation(lv_obj_t *TargetObject, int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 0, 242);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_0);

}
void topCtrlUp_Animation(lv_obj_t *TargetObject, int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 0, -242);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_gamePadBtn(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED) {
        app_ui_event_mainToGamePad(e);
    }
    if (event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_GamePadAppScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_NesBtn(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED) {
        app_ui_event_mainToNesEmulator(e);
    }
}
void ui_event_RemoteBtn(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED) {
        app_ui_event_mainToRcAPP(e);
    }
    if (event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_RcAppScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_returnBtnInGamePad(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_mainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
        app_ui_event_gameReturnBtn(e);
    }
}
void ui_event_GamePadTipsBtn(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_GamePadAppSettingScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0);
    }
}
void ui_event_bindBtn(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED) {
        app_ui_event_espnow_bind(e);
    }
}
void ui_event_returnBtnInEspDrone(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_mainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
        app_ui_event_rcReturnBtn(e);
    }
}
void ui_event_hidModeSelectBtn(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED) {
        app_ui_event_hid_mode_select(e);
    }
}
void ui_event_gamePadSettingCloseBtn(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_GamePadAppScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0);
    }
}
void ui_event_rockerCalibrationStartBtn(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED) {
        app_ui_event_rocker_calibration(e);
    }
}
void ui_event_VibrationFeedbackBtn(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED) {
        app_ui_event_vibration_feedback(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                        false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_mainScreen_screen_init();
    ui_GamePadAppScreen_screen_init();
    ui_RcAppScreen_screen_init();
    ui_GamePadAppSettingScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_mainScreen);
}
