// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: BOX_REMOTE_CONTROL

#ifndef _BOX_REMOTE_CONTROL_UI_H
#define _BOX_REMOTE_CONTROL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void topCtrlDown_Animation(lv_obj_t *TargetObject, int delay);
void topCtrlUp_Animation(lv_obj_t *TargetObject, int delay);
// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
extern lv_obj_t *ui_mainScreen;
extern lv_obj_t *ui_GamePadPanel;
void ui_event_gamePadBtn(lv_event_t *e);
extern lv_obj_t *ui_gamePadBtn;
extern lv_obj_t *ui_gamePadBtnImage;
extern lv_obj_t *ui_gamePadLab;
extern lv_obj_t *ui_nesPanel;
void ui_event_NesBtn(lv_event_t *e);
extern lv_obj_t *ui_NesBtn;
extern lv_obj_t *ui_NesBtnImage;
extern lv_obj_t *ui_NesLab;
extern lv_obj_t *ui_rcPanel;
void ui_event_RemoteBtn(lv_event_t *e);
extern lv_obj_t *ui_RemoteBtn;
extern lv_obj_t *ui_RemoteBtnImage;
extern lv_obj_t *ui_RemoteLab;
extern lv_obj_t *ui_SettingPanel;
extern lv_obj_t *ui_SettingBtn;
extern lv_obj_t *ui_SettingBtnImage;
extern lv_obj_t *ui_SettingLab;
extern lv_obj_t *ui_MainScreenStatePanel;
extern lv_obj_t *ui_TimeLabel;
extern lv_obj_t *ui_bluetoothImage;
extern lv_obj_t *ui_WifiImage;
extern lv_obj_t *ui_usbImage;
extern lv_obj_t *ui_powerBar;
extern lv_obj_t *ui_powerLab;
extern lv_obj_t *ui_Panel1;
// SCREEN: ui_GamePadAppScreen
void ui_GamePadAppScreen_screen_init(void);
extern lv_obj_t *ui_GamePadAppScreen;
extern lv_obj_t *ui_GameTopPanel;
void ui_event_returnBtnInGamePad(lv_event_t *e);
extern lv_obj_t *ui_returnBtnInGamePad;
extern lv_obj_t *ui_returnBtnInGamePadIcon;
extern lv_obj_t *ui_returnLabInGamePad;
extern lv_obj_t *ui_gameScreenTitle;
void ui_event_GamePadTipsBtn(lv_event_t *e);
extern lv_obj_t *ui_GamePadTipsBtn;
extern lv_obj_t *ui_GamePadTipsBtnIcon;
extern lv_obj_t *ui_upBtn;
extern lv_obj_t *ui_upBtnIcon;
extern lv_obj_t *ui_leftBtn;
extern lv_obj_t *ui_leftBtnIcon;
extern lv_obj_t *ui_rightBtn;
extern lv_obj_t *ui_rightBtnIcon;
extern lv_obj_t *ui_downBtn;
extern lv_obj_t *ui_downBtnIcon;
extern lv_obj_t *ui_yBtn;
extern lv_obj_t *ui_xKeyLab;
extern lv_obj_t *ui_bBtn;
extern lv_obj_t *ui_bKeyLab;
extern lv_obj_t *ui_aBtn;
extern lv_obj_t *ui_aKeyLab;
extern lv_obj_t *ui_xBtn;
extern lv_obj_t *ui_yKeyLab;
extern lv_obj_t *ui_lbBtn;
extern lv_obj_t *ui_lbBtnLab;
extern lv_obj_t *ui_ltBtn;
extern lv_obj_t *ui_ltBtnLab;
extern lv_obj_t *ui_rbBtn;
extern lv_obj_t *ui_rbBtnLab;
extern lv_obj_t *ui_rtBtn;
extern lv_obj_t *ui_rtBtnLab;
extern lv_obj_t *ui_leftRocker;
extern lv_obj_t *ui_leftRockerBtn;
extern lv_obj_t *ui_rightRocker;
extern lv_obj_t *ui_rightRockerBtn;
extern lv_obj_t *ui_selectBtn;
extern lv_obj_t *ui_selectBtnLab;
extern lv_obj_t *ui_startBtn;
extern lv_obj_t *ui_startBtnLab;
extern lv_obj_t *ui_GamePadStatePanel;
extern lv_obj_t *ui_TimeLabel1;
extern lv_obj_t *ui_bluetoothImage1;
extern lv_obj_t *ui_WifiImage1;
extern lv_obj_t *ui_usbImage1;
extern lv_obj_t *ui_powerBar1;
extern lv_obj_t *ui_powerLab1;
// SCREEN: ui_RcAppScreen
void ui_RcAppScreen_screen_init(void);
extern lv_obj_t *ui_RcAppScreen;
extern lv_obj_t *ui_EspDroneStatePanel;
extern lv_obj_t *ui_TimeLabel2;
extern lv_obj_t *ui_bluetoothImage2;
extern lv_obj_t *ui_WifiImage2;
extern lv_obj_t *ui_usbImage2;
extern lv_obj_t *ui_powerBar2;
extern lv_obj_t *ui_powerLab2;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_dLeftRockerPanel;
extern lv_obj_t *ui_dLeftRockerBtn;
extern lv_obj_t *ui_dRightRockerPanel;
extern lv_obj_t *ui_dRightRockerBtn;
void ui_event_bindBtn(lv_event_t *e);
extern lv_obj_t *ui_bindBtn;
extern lv_obj_t *ui_RcTopPanel;
void ui_event_returnBtnInEspDrone(lv_event_t *e);
extern lv_obj_t *ui_returnBtnInEspDrone;
extern lv_obj_t *ui_returnBtnInEspDroneIcon;
extern lv_obj_t *ui_returnLabInEspDrone;
extern lv_obj_t *ui_espDroneTitle;
extern lv_obj_t *ui_RcDataPanel;
extern lv_obj_t *ui_dPLabel;
extern lv_obj_t *ui_dRLabel;
extern lv_obj_t *ui_dTLabel;
extern lv_obj_t *ui_dYLabel;
extern lv_obj_t *ui_dPLabelData;
extern lv_obj_t *ui_dRLabelData;
extern lv_obj_t *ui_dTLabelData;
extern lv_obj_t *ui_dYLabelData;
// SCREEN: ui_GamePadAppSettingScreen
void ui_GamePadAppSettingScreen_screen_init(void);
extern lv_obj_t *ui_GamePadAppSettingScreen;
extern lv_obj_t *ui_hidModeSelectPanel;
extern lv_obj_t *ui_hidSelectLab;
void ui_event_hidModeSelectBtn(lv_event_t *e);
extern lv_obj_t *ui_hidModeSelectBtn;
extern lv_obj_t *ui_hidModeSelectBtnPart;
extern lv_obj_t *ui_hidModeSelectLab;
extern lv_obj_t *ui_GameSettingTopPanel;
void ui_event_gamePadSettingCloseBtn(lv_event_t *e);
extern lv_obj_t *ui_gamePadSettingCloseBtn;
extern lv_obj_t *ui_gamePadSettingCloseBtnIcon;
extern lv_obj_t *ui_GamePadSettingLabel;
extern lv_obj_t *ui_GameModeSettingStatePanel;
extern lv_obj_t *ui_TimeLabel3;
extern lv_obj_t *ui_bluetoothImage3;
extern lv_obj_t *ui_WifiImage3;
extern lv_obj_t *ui_usbImage3;
extern lv_obj_t *ui_powerBar3;
extern lv_obj_t *ui_powerLab3;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_RockerCalibrationPanel;
extern lv_obj_t *ui_rockerCalibrationLab;
void ui_event_rockerCalibrationStartBtn(lv_event_t *e);
extern lv_obj_t *ui_rockerCalibrationStartBtn;
extern lv_obj_t *ui_rockerCalibrationStartBtnText;
extern lv_obj_t *ui_VibrationFeedbackPanel;
extern lv_obj_t *ui_VibrationFeedbackLab;
void ui_event_VibrationFeedbackBtn(lv_event_t *e);
extern lv_obj_t *ui_VibrationFeedbackBtn;
extern lv_obj_t *ui_VibrationFeedbackBtnPart;
extern lv_obj_t *ui_VibrationFeedbackStateLab;
extern lv_obj_t *ui_RockerCalibrationSettingPanel;
extern lv_obj_t *ui_rockerCalibrationTipsLab;
extern lv_obj_t *ui_leftRockerCalibrate;
extern lv_obj_t *ui_leftRockerCalibrateBtn;
extern lv_obj_t *ui_rightRockerCalibrate;
extern lv_obj_t *ui_rightRockerCalibrateBtn;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE(ui_img_game_pad_app_png);    // assets/game_pad_app.png
LV_IMG_DECLARE(ui_img_nes_app_png);    // assets/nes_app.png
LV_IMG_DECLARE(ui_img_rc_app_png);    // assets/rc_app.png
LV_IMG_DECLARE(ui_img_setting_app_png);    // assets/setting_app.png
LV_IMG_DECLARE(ui_img_ble_icon_20px_png);    // assets/ble_icon_20px.png
LV_IMG_DECLARE(ui_img_wifi_icon_18px_png);    // assets/wifi_icon_18px.png
LV_IMG_DECLARE(ui_img_usb_icon_20px_png);    // assets/usb_icon_20px.png
LV_IMG_DECLARE(ui_img_return_btn_16px_png);    // assets/return_btn_16px.png
LV_IMG_DECLARE(ui_img_setting_icon_20px_png);    // assets/setting_icon_20px.png
LV_IMG_DECLARE(ui_img_up_btn_png);    // assets/up_btn.png
LV_IMG_DECLARE(ui_img_left_btn_png);    // assets/left_btn.png
LV_IMG_DECLARE(ui_img_right_btn_png);    // assets/right_btn.png
LV_IMG_DECLARE(ui_img_down_btn_png);    // assets/down_btn.png
LV_IMG_DECLARE(ui_img_espnow_bind_png);    // assets/espnow_bind.png
LV_IMG_DECLARE(ui_img_ble_28_png);    // assets/ble_28.png
LV_IMG_DECLARE(ui_img_brilliance_28_png);    // assets/brilliance_28.png
LV_IMG_DECLARE(ui_img_usb_28_png);    // assets/usb_28.png
LV_IMG_DECLARE(ui_img_vibration_28_png);    // assets/vibration_28.png
LV_IMG_DECLARE(ui_img_volume_ctrl_26_png);    // assets/volume_ctrl_26.png
LV_IMG_DECLARE(ui_img_wifi_28_png);    // assets/wifi_28.png

LV_FONT_DECLARE(ui_font_SourceHanSansCN14);
LV_FONT_DECLARE(ui_font_SourceHanSansCN20);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
