// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.4
// Project name: box_reset_mode

#ifndef _BOX_RESET_MODE_UI_H
#define _BOX_RESET_MODE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void sleep_body_up_down_Animation(lv_obj_t *TargetObject, int delay);
void listen_eye_blink_Animation(lv_obj_t *TargetObject, int delay);
void listen_eye_screen_move_Animation(lv_obj_t *TargetObject, int delay);
void get_eye_blink_Animation(lv_obj_t *TargetObject, int delay);
// SCREEN: ui_ScreenSetup
void ui_ScreenSetup_screen_init(void);
extern lv_obj_t *ui_ScreenSetup;
extern lv_obj_t *ui_ImageSetupTextBg;
extern lv_obj_t *ui_PanelSetupSteps;
extern lv_obj_t *ui_LabelSetupStepContent;
extern lv_obj_t *ui_LabelSetupStepTile;
void ui_event_ButtonSetup(lv_event_t *e);
extern lv_obj_t *ui_ButtonSetup;
extern lv_obj_t *ui_LabelSetupBtn;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE(ui_img_setup_bg_png);    // assets\setup_bg.png
LV_IMG_DECLARE(ui_img_setup_text_bg_png);    // assets\setup_text_bg.png

LV_FONT_DECLARE(ui_font_PingFangEN14);
LV_FONT_DECLARE(ui_font_PingFangEN16);
LV_FONT_DECLARE(ui_font_PingFangEN20);

// EVENT: event for ESP32_S3_BOX_Lite
lv_group_t *ui_get_btn_op_group(void);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
