// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.4
// Project name: box_reset_mode

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void EventBtnSetupClick(lv_event_t *e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
