// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: chat_gpt

#include "../ui.h"

void ui_ScreenListen_screen_init(void)
{
    ui_ScreenListen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenListen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScreenListen, &ui_img_setup_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBodyShadow = lv_img_create(ui_ScreenListen);
    lv_img_set_src(ui_ImageBodyShadow, &ui_img_body_shadow_png);
    lv_obj_set_width(ui_ImageBodyShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageBodyShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageBodyShadow, 0);
    lv_obj_set_y(ui_ImageBodyShadow, -45);
    lv_obj_set_align(ui_ImageBodyShadow, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ImageBodyShadow, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBodyShadow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelSleep = lv_obj_create(ui_ScreenListen);
    lv_obj_set_width(ui_PanelSleep, 320);
    lv_obj_set_height(ui_PanelSleep, 240);
    lv_obj_clear_flag(ui_PanelSleep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSleep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSleep, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSleep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSleep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelSleep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelSleep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelSleep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelSleep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_PanelSleep, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelSleep, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelSleep, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelSleep, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelSleep, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelSleep, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelSleep, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelSleep, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelSleep, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ImageSleepBody = lv_img_create(ui_PanelSleep);
    lv_img_set_src(ui_ImageSleepBody, &ui_img_body_png);
    lv_obj_set_width(ui_ImageSleepBody, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSleepBody, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageSleepBody, 101);
    lv_obj_set_y(ui_ImageSleepBody, 53);
    lv_obj_add_flag(ui_ImageSleepBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST |
                    LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_ImageSleepBody, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_ImageSleepBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ImageSleepBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ImageSleepBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_ImageSleepBody);
    lv_img_set_src(ui_Image3, &ui_img_body_eye_screen_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, 10);
    lv_obj_set_y(ui_Image3, 5);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageSleepEye = lv_img_create(ui_Image3);
    lv_img_set_src(ui_ImageSleepEye, &ui_img_sleep_body_eyes_png);
    lv_obj_set_width(ui_ImageSleepEye, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSleepEye, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageSleepEye, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSleepEye, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSleepEye, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerBigZ = lv_obj_create(ui_PanelSleep);
    lv_obj_set_width(ui_ContainerBigZ, 27);
    lv_obj_set_height(ui_ContainerBigZ, 22);
    lv_obj_set_x(ui_ContainerBigZ, 83);
    lv_obj_set_y(ui_ContainerBigZ, -28);
    lv_obj_set_align(ui_ContainerBigZ, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerBigZ, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContainerBigZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerBigZ, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerBigZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ContainerBigZ, &ui_img_sleep_big_z_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ContainerBigZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerBigZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerBigZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerBigZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerBigZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerBigZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ContainerBigZ, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerBigZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerBigZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContainerBigZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContainerBigZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerBigZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerBigZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerBigZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerBigZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ContainerBigZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerBigZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ContainerSmallZ = lv_obj_create(ui_PanelSleep);
    lv_obj_set_width(ui_ContainerSmallZ, 23);
    lv_obj_set_height(ui_ContainerSmallZ, 17);
    lv_obj_set_x(ui_ContainerSmallZ, 106);
    lv_obj_set_y(ui_ContainerSmallZ, -34);
    lv_obj_set_align(ui_ContainerSmallZ, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerSmallZ, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContainerSmallZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerSmallZ, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerSmallZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ContainerSmallZ, &ui_img_sleep_small_z_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ContainerSmallZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerSmallZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerSmallZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerSmallZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerSmallZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerSmallZ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ContainerSmallZ, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerSmallZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerSmallZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContainerSmallZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContainerSmallZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerSmallZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerSmallZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerSmallZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerSmallZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ContainerSmallZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerSmallZ, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_PanelListen = lv_obj_create(ui_ScreenListen);
    lv_obj_set_width(ui_PanelListen, 320);
    lv_obj_set_height(ui_PanelListen, 240);
    lv_obj_add_flag(ui_PanelListen, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelListen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelListen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelListen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelListen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelListen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelListen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelListen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelListen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelListen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_PanelListen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelListen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelListen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelListen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelListen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelListen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelListen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelListen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelListen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ImageListenBackGlow = lv_img_create(ui_PanelListen);
    lv_img_set_src(ui_ImageListenBackGlow, &ui_img_listen_back_glow_png);
    lv_obj_set_width(ui_ImageListenBackGlow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageListenBackGlow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageListenBackGlow, 0);
    lv_obj_set_y(ui_ImageListenBackGlow, -17);
    lv_obj_set_align(ui_ImageListenBackGlow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageListenBackGlow, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageListenBackGlow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageListenBody = lv_img_create(ui_ImageListenBackGlow);
    lv_img_set_src(ui_ImageListenBody, &ui_img_body_png);
    lv_obj_set_width(ui_ImageListenBody, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageListenBody, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageListenBody, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageListenBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST |
                    LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_ImageListenBody, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ImageListenBody, &ui_img_body_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageListenEyeScreen = lv_img_create(ui_ImageListenBody);
    lv_img_set_src(ui_ImageListenEyeScreen, &ui_img_body_eye_screen_png);
    lv_obj_set_width(ui_ImageListenEyeScreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageListenEyeScreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageListenEyeScreen, 10);
    lv_obj_set_y(ui_ImageListenEyeScreen, 5);
    lv_obj_set_align(ui_ImageListenEyeScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageListenEyeScreen, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageListenEyeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageListenEye = lv_img_create(ui_ImageListenEyeScreen);
    lv_img_set_src(ui_ImageListenEye, &ui_img_listen_body_eyes_1_png);
    lv_obj_set_width(ui_ImageListenEye, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageListenEye, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageListenEye, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageListenEye, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageListenEye, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelGet = lv_obj_create(ui_ScreenListen);
    lv_obj_set_width(ui_PanelGet, 320);
    lv_obj_set_height(ui_PanelGet, 240);
    lv_obj_add_flag(ui_PanelGet, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelGet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelGet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelGet, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelGet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelGet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelGet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelGet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelGet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelGet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_PanelGet, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelGet, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelGet, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelGet, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelGet, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelGet, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelGet, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelGet, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelGet, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ImageGetBackGlow = lv_img_create(ui_PanelGet);
    lv_img_set_src(ui_ImageGetBackGlow, &ui_img_listen_back_glow_png);
    lv_obj_set_width(ui_ImageGetBackGlow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageGetBackGlow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageGetBackGlow, 0);
    lv_obj_set_y(ui_ImageGetBackGlow, -17);
    lv_obj_set_align(ui_ImageGetBackGlow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageGetBackGlow, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageGetBackGlow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageGetBody = lv_img_create(ui_ImageGetBackGlow);
    lv_img_set_src(ui_ImageGetBody, &ui_img_body_png);
    lv_obj_set_width(ui_ImageGetBody, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageGetBody, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageGetBody, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageGetBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST |
                    LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_ImageGetBody, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ImageGetBody, &ui_img_body_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageGetEyeScreen = lv_img_create(ui_ImageGetBody);
    lv_img_set_src(ui_ImageGetEyeScreen, &ui_img_body_eye_screen_png);
    lv_obj_set_width(ui_ImageGetEyeScreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageGetEyeScreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageGetEyeScreen, 0);
    lv_obj_set_y(ui_ImageGetEyeScreen, 5);
    lv_obj_set_align(ui_ImageGetEyeScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageGetEyeScreen, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageGetEyeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageGetEye = lv_img_create(ui_ImageGetEyeScreen);
    lv_img_set_src(ui_ImageGetEye, &ui_img_listen_body_eyes_1_png);
    lv_obj_set_width(ui_ImageGetEye, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageGetEye, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageGetEye, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageGetEye, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageGetEye, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelReply = lv_obj_create(ui_ScreenListen);
    lv_obj_set_width(ui_PanelReply, 320);
    lv_obj_set_height(ui_PanelReply, 240);
    lv_obj_add_flag(ui_PanelReply, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelReply, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelReply, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelReply, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelReply, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelReply, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelReply, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelReply, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelReply, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelReply, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_PanelReply, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelReply, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelReply, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelReply, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelReply, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelReply, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelReply, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelReply, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelReply, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ImageReplyBg = lv_img_create(ui_PanelReply);
    lv_img_set_src(ui_ImageReplyBg, &ui_img_reply_chatgpt_bg_png);
    lv_obj_set_width(ui_ImageReplyBg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageReplyBg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageReplyBg, 0);
    lv_obj_set_y(ui_ImageReplyBg, 5);
    lv_obj_set_align(ui_ImageReplyBg, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ImageReplyBg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageReplyBg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelReplyQuestion = lv_label_create(ui_ImageReplyBg);
    lv_obj_set_width(ui_LabelReplyQuestion, 205);
    lv_obj_set_height(ui_LabelReplyQuestion, 25);
    lv_obj_set_x(ui_LabelReplyQuestion, 20);
    lv_obj_set_y(ui_LabelReplyQuestion, -1);
    lv_obj_set_align(ui_LabelReplyQuestion, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_LabelReplyQuestion, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabelReplyQuestion, "");
    lv_obj_clear_flag(ui_LabelReplyQuestion, LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scroll_dir(ui_LabelReplyQuestion, LV_DIR_HOR);
    lv_obj_set_style_text_color(ui_LabelReplyQuestion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelReplyQuestion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelReplyQuestion, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelReplyQuestion, &ui_font_KaiTiCN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageRelyBody = lv_img_create(ui_PanelReply);
    lv_img_set_src(ui_ImageRelyBody, &ui_img_reply_body_png);
    lv_obj_set_width(ui_ImageRelyBody, 52);
    lv_obj_set_height(ui_ImageRelyBody, 54);
    lv_obj_set_x(ui_ImageRelyBody, -27);
    lv_obj_set_y(ui_ImageRelyBody, 0);
    lv_obj_set_align(ui_ImageRelyBody, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageRelyBody, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageRelyBody, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageReplyBodyShadow = lv_img_create(ui_ImageRelyBody);
    lv_img_set_src(ui_ImageReplyBodyShadow, &ui_img_reply_small_shadow_png);
    lv_obj_set_width(ui_ImageReplyBodyShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageReplyBodyShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageReplyBodyShadow, 0);
    lv_obj_set_y(ui_ImageReplyBodyShadow, 4);
    lv_obj_set_align(ui_ImageReplyBodyShadow, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ImageReplyBodyShadow, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_clear_flag(ui_ImageReplyBodyShadow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerReplyContent = lv_obj_create(ui_PanelReply);
    lv_obj_set_height(ui_ContainerReplyContent, 160);
    lv_obj_set_width(ui_ContainerReplyContent, LV_SIZE_CONTENT);   /// 268
    lv_obj_set_x(ui_ContainerReplyContent, -20);
    lv_obj_set_y(ui_ContainerReplyContent, 60);
    lv_obj_set_align(ui_ContainerReplyContent, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_scroll_dir(ui_ContainerReplyContent, LV_DIR_VER);
    lv_obj_set_style_radius(ui_ContainerReplyContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerReplyContent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerReplyContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ContainerReplyContent, &ui_img_sleep_big_z_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ContainerReplyContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerReplyContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerReplyContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerReplyContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerReplyContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerReplyContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ContainerReplyContent, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerReplyContent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerReplyContent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContainerReplyContent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContainerReplyContent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerReplyContent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerReplyContent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerReplyContent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerReplyContent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ContainerReplyContent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerReplyContent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LabelReplyContent = lv_label_create(ui_ContainerReplyContent);
    lv_obj_set_width(ui_LabelReplyContent, 250);
    lv_obj_set_height(ui_LabelReplyContent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelReplyContent, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelReplyContent, "");
    lv_obj_set_style_text_color(ui_LabelReplyContent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelReplyContent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelReplyContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelReplyContent, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelReplyContent, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelReplyContent, &ui_font_KaiTiCN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageReplyLogo = lv_img_create(ui_PanelReply);
    lv_img_set_src(ui_ImageReplyLogo, &ui_img_reply_chatgpt_logo_png);
    lv_obj_set_width(ui_ImageReplyLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageReplyLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageReplyLogo, -282);
    lv_obj_set_y(ui_ImageReplyLogo, 60);
    lv_obj_set_align(ui_ImageReplyLogo, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageReplyLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageReplyLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelListenSpeak = lv_label_create(ui_ScreenListen);
    lv_obj_set_width(ui_LabelListenSpeak, 250);
    lv_obj_set_height(ui_LabelListenSpeak, 24);
    lv_obj_set_x(ui_LabelListenSpeak, 0);
    lv_obj_set_y(ui_LabelListenSpeak, -30);
    lv_obj_set_align(ui_LabelListenSpeak, LV_ALIGN_BOTTOM_MID);
    lv_label_set_long_mode(ui_LabelListenSpeak, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabelListenSpeak, "");
    lv_obj_add_flag(ui_LabelListenSpeak, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_LabelListenSpeak, LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scroll_dir(ui_LabelListenSpeak, LV_DIR_HOR);
    lv_obj_set_style_text_color(ui_LabelListenSpeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelListenSpeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelListenSpeak, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelListenSpeak, &ui_font_KaiTiCN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageListenSettings = lv_img_create(ui_ScreenListen);
    lv_img_set_src(ui_ImageListenSettings, &ui_img_settings_icon_png);
    lv_obj_set_width(ui_ImageListenSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageListenSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageListenSettings, -119);
    lv_obj_set_y(ui_ImageListenSettings, -85);
    lv_obj_set_align(ui_ImageListenSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageListenSettings, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageListenSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ImageListenSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ImageListenSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImageListenSettings, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_PanelSleep, ui_event_PanelSleep, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImageListenSettings, ui_event_ImageListenSettings, LV_EVENT_ALL, NULL);

}
