// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: chat_gpt

#include "../ui.h"

void ui_ScreenSettings_screen_init(void)
{
    ui_ScreenSettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScreenSettings, &ui_img_setup_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSettingsTile = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_LabelSettingsTile, 230);
    lv_obj_set_height(ui_LabelSettingsTile, 23);
    lv_obj_set_x(ui_LabelSettingsTile, 45);
    lv_obj_set_y(ui_LabelSettingsTile, 15);
    lv_label_set_text(ui_LabelSettingsTile, "Settings");
    lv_obj_set_style_text_color(ui_LabelSettingsTile, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSettingsTile, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSettingsTile, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSettingsTile, &ui_font_PingFangEN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSettings = lv_obj_create(ui_ScreenSettings);
    lv_obj_set_width(ui_PanelSettings, lv_pct(100));
    lv_obj_set_height(ui_PanelSettings, lv_pct(79));
    lv_obj_set_align(ui_PanelSettings, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_PanelSettings, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelSettings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_set_style_radius(ui_PanelSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_PanelSettings, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelSettings, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelSettings, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelSettings, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelSettings, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelSettings, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelSettings, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelSettings, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelSettings, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_PanelSettingsSplitBar = lv_obj_create(ui_PanelSettings);
    lv_obj_set_width(ui_PanelSettingsSplitBar, lv_pct(100));
    lv_obj_set_height(ui_PanelSettingsSplitBar, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_PanelSettingsSplitBar, -2);
    lv_obj_set_y(ui_PanelSettingsSplitBar, 47);
    lv_obj_set_align(ui_PanelSettingsSplitBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSettingsSplitBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSettingsSplitBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSettingsSplitBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSettingsSplitBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSettingsSplitBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelSettingsSplitBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelSettingsSplitBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelSettingsSplitBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelSettingsSplitBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelSettingsSplitBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelSettingsSplitBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSettingsSplitBarLeft = lv_obj_create(ui_PanelSettingsSplitBar);
    lv_obj_set_height(ui_PanelSettingsSplitBarLeft, 2);
    lv_obj_set_width(ui_PanelSettingsSplitBarLeft, lv_pct(50));
    lv_obj_set_align(ui_PanelSettingsSplitBarLeft, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_PanelSettingsSplitBarLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSettingsSplitBarLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSettingsSplitBarLeft, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSettingsSplitBarLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PanelSettingsSplitBarLeft, lv_color_hex(0x6E47BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelSettingsSplitBarLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelSettingsSplitBarLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PanelSettingsSplitBarLeft, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSettingsSplitBarLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsSettingsSplitBarRight = lv_obj_create(ui_PanelSettingsSplitBar);
    lv_obj_set_height(ui_SettingsSettingsSplitBarRight, 2);
    lv_obj_set_width(ui_SettingsSettingsSplitBarRight, lv_pct(50));
    lv_obj_set_align(ui_SettingsSettingsSplitBarRight, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_SettingsSettingsSplitBarRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingsSettingsSplitBarRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SettingsSettingsSplitBarRight, lv_color_hex(0x6E47BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsSettingsSplitBarRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SettingsSettingsSplitBarRight, lv_color_hex(0x000000),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SettingsSettingsSplitBarRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SettingsSettingsSplitBarRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SettingsSettingsSplitBarRight, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingsSettingsSplitBarRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSettingsRegion = lv_obj_create(ui_PanelSettings);
    lv_obj_set_width(ui_PanelSettingsRegion, lv_pct(100));
    lv_obj_set_height(ui_PanelSettingsRegion, lv_pct(19));
    lv_obj_set_align(ui_PanelSettingsRegion, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_PanelSettingsRegion, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelSettingsRegion, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSettingsRegion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSettingsRegion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSettingsRegion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSettingsRegion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSettingsRegion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelSettingsRegion, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelSettingsRegion, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelSettingsRegion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelSettingsRegion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelSettingsRegion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelSettingsRegion, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_PanelSettingsRegion, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelSettingsRegion, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelSettingsRegion, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelSettingsRegion, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelSettingsRegion, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelSettingsRegion, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelSettingsRegion, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelSettingsRegion, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelSettingsRegion, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LabelSettingsRegion = lv_label_create(ui_PanelSettingsRegion);
    lv_obj_set_width(ui_LabelSettingsRegion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSettingsRegion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSettingsRegion, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelSettingsRegion, "Region Select");
    lv_obj_set_style_text_color(ui_LabelSettingsRegion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSettingsRegion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSettingsRegion, &ui_font_PingFangEN16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownSettingsRegion = lv_dropdown_create(ui_PanelSettingsRegion);
    lv_dropdown_set_options(ui_DropdownSettingsRegion, "Espressif\nOpenAI");
    lv_obj_set_width(ui_DropdownSettingsRegion, lv_pct(33));
    lv_obj_set_height(ui_DropdownSettingsRegion, lv_pct(100));
    lv_obj_set_x(ui_DropdownSettingsRegion, 2);
    lv_obj_set_y(ui_DropdownSettingsRegion, -9);
    lv_obj_set_align(ui_DropdownSettingsRegion, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_DropdownSettingsRegion, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_outline_width(ui_DropdownSettingsRegion, 0, LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_DropdownSettingsRegion, 0, LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_DropdownSettingsRegion, 0, LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_DropdownSettingsRegion, 0, LV_STATE_FOCUS_KEY);

    lv_obj_set_style_text_align(ui_DropdownSettingsRegion, LV_TEXT_ALIGN_CENTER, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ImageSettingsBack = lv_img_create(ui_ScreenSettings);
    lv_img_set_src(ui_ImageSettingsBack, &ui_img_settings_back_png);
    lv_obj_set_width(ui_ImageSettingsBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSettingsBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageSettingsBack, 10);
    lv_obj_set_y(ui_ImageSettingsBack, 10);
    lv_obj_add_flag(ui_ImageSettingsBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_add_flag(ui_ImageSettingsBack, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSettingsBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_border_color(ui_ImageSettingsBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ImageSettingsBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImageSettingsBack, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ImageSettingsReset = lv_img_create(ui_ScreenSettings);
    lv_img_set_src(ui_ImageSettingsReset, &ui_img_reset_icon_png);
    lv_obj_set_width(ui_ImageSettingsReset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSettingsReset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageSettingsReset, -10);
    lv_obj_set_y(ui_ImageSettingsReset, 10);
    lv_obj_set_align(ui_ImageSettingsReset, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageSettingsReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_add_flag(ui_ImageSettingsReset, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSettingsReset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_border_color(ui_ImageSettingsReset, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ImageSettingsReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImageSettingsReset, 5, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_add_event_cb(ui_DropdownSettingsRegion, ui_event_DropdownSettingsRegion, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImageSettingsBack, ui_event_ImageSettingsBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImageSettingsReset, ui_event_ImageSettingsReset, LV_EVENT_ALL, NULL);
}
