// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: BOX_REMOTE_CONTROL

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void app_ui_event_mainToGamePad(lv_event_t *e);
void app_ui_event_mainToNesEmulator(lv_event_t *e);
void app_ui_event_mainToRcAPP(lv_event_t *e);
void app_ui_event_gameReturnBtn(lv_event_t *e);
void app_ui_event_espnow_bind(lv_event_t *e);
void app_ui_event_rcReturnBtn(lv_event_t *e);
void app_ui_event_hid_mode_select(lv_event_t *e);
void app_ui_event_rocker_calibration(lv_event_t *e);
void app_ui_event_vibration_feedback(lv_event_t *e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
