// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: chat_gpt

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void EventBtnSetupClick(lv_event_t * e);
void EventWifiResetConfirmClick(lv_event_t * e);
void EventPanelSleepClickCb(lv_event_t * e);
// void EventSettingsRegionValueChange(lv_event_t * e); /*This function is for server selection currently not supported*/
void EventResetConfirm(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
