// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: BOX_REMOTE_CONTROL

#include "../ui.h"

void ui_GamePadAppSettingScreen_screen_init(void)
{
    ui_GamePadAppSettingScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GamePadAppSettingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GamePadAppSettingScreen, lv_color_hex(0xFFF8E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GamePadAppSettingScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hidModeSelectPanel = lv_obj_create(ui_GamePadAppSettingScreen);
    lv_obj_set_width(ui_hidModeSelectPanel, 300);
    lv_obj_set_height(ui_hidModeSelectPanel, 38);
    lv_obj_set_x(ui_hidModeSelectPanel, 0);
    lv_obj_set_y(ui_hidModeSelectPanel, -40);
    lv_obj_set_align(ui_hidModeSelectPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_hidModeSelectPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_hidModeSelectPanel, 19, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_hidModeSelectPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hidModeSelectPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_hidModeSelectPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_hidModeSelectPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_hidModeSelectPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_hidModeSelectPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hidSelectLab = lv_label_create(ui_hidModeSelectPanel);
    lv_obj_set_width(ui_hidSelectLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hidSelectLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hidSelectLab, -51);
    lv_obj_set_y(ui_hidSelectLab, 0);
    lv_obj_set_align(ui_hidSelectLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hidSelectLab, "HID Connection Mode");
    lv_obj_set_style_text_font(ui_hidSelectLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hidModeSelectBtn = lv_btn_create(ui_hidModeSelectPanel);
    lv_obj_set_width(ui_hidModeSelectBtn, 100);
    lv_obj_set_height(ui_hidModeSelectBtn, 30);
    lv_obj_set_x(ui_hidModeSelectBtn, 95);
    lv_obj_set_y(ui_hidModeSelectBtn, 0);
    lv_obj_set_align(ui_hidModeSelectBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hidModeSelectBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_hidModeSelectBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_hidModeSelectBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_hidModeSelectBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hidModeSelectBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_hidModeSelectBtn, lv_color_hex(0xF2A860), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_hidModeSelectBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_hidModeSelectBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_hidModeSelectBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_hidModeSelectBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_hidModeSelectBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_hidModeSelectBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_hidModeSelectBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_hidModeSelectBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_hidModeSelectBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hidModeSelectBtnPart = lv_btn_create(ui_hidModeSelectBtn);
    lv_obj_set_width(ui_hidModeSelectBtnPart, 48);
    lv_obj_set_height(ui_hidModeSelectBtnPart, 22);
    lv_obj_set_x(ui_hidModeSelectBtnPart, -22);
    lv_obj_set_y(ui_hidModeSelectBtnPart, 0);
    lv_obj_set_align(ui_hidModeSelectBtnPart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hidModeSelectBtnPart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_hidModeSelectBtnPart,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_hidModeSelectBtnPart, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_hidModeSelectBtnPart, lv_color_hex(0xF2A860), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hidModeSelectBtnPart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_hidModeSelectBtnPart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_hidModeSelectBtnPart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_hidModeSelectBtnPart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_hidModeSelectBtnPart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_hidModeSelectBtnPart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_hidModeSelectBtnPart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hidModeSelectLab = lv_label_create(ui_hidModeSelectBtnPart);
    lv_obj_set_width(ui_hidModeSelectLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hidModeSelectLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_hidModeSelectLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hidModeSelectLab, "USB");
    lv_obj_set_style_text_font(ui_hidModeSelectLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GameSettingTopPanel = lv_obj_create(ui_GamePadAppSettingScreen);
    lv_obj_set_width(ui_GameSettingTopPanel, 320);
    lv_obj_set_height(ui_GameSettingTopPanel, 25);
    lv_obj_set_x(ui_GameSettingTopPanel, 0);
    lv_obj_set_y(ui_GameSettingTopPanel, -83);
    lv_obj_set_align(ui_GameSettingTopPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GameSettingTopPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GameSettingTopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GameSettingTopPanel, lv_color_hex(0xF2A860), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GameSettingTopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GameSettingTopPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GameSettingTopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GameSettingTopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_GameSettingTopPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gamePadSettingCloseBtn = lv_btn_create(ui_GameSettingTopPanel);
    lv_obj_set_width(ui_gamePadSettingCloseBtn, 40);
    lv_obj_set_height(ui_gamePadSettingCloseBtn, 25);
    lv_obj_set_x(ui_gamePadSettingCloseBtn, -140);
    lv_obj_set_y(ui_gamePadSettingCloseBtn, 0);
    lv_obj_set_align(ui_gamePadSettingCloseBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gamePadSettingCloseBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_gamePadSettingCloseBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_gamePadSettingCloseBtn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gamePadSettingCloseBtn, lv_color_hex(0xF2A860), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gamePadSettingCloseBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_gamePadSettingCloseBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_gamePadSettingCloseBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_gamePadSettingCloseBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_gamePadSettingCloseBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_gamePadSettingCloseBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_gamePadSettingCloseBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gamePadSettingCloseBtnIcon = lv_img_create(ui_gamePadSettingCloseBtn);
    lv_img_set_src(ui_gamePadSettingCloseBtnIcon, &ui_img_return_btn_16px_png);
    lv_obj_set_width(ui_gamePadSettingCloseBtnIcon, 16);
    lv_obj_set_height(ui_gamePadSettingCloseBtnIcon, 16);
    lv_obj_set_align(ui_gamePadSettingCloseBtnIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gamePadSettingCloseBtnIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_gamePadSettingCloseBtnIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GamePadSettingLabel = lv_label_create(ui_GameSettingTopPanel);
    lv_obj_set_width(ui_GamePadSettingLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GamePadSettingLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GamePadSettingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GamePadSettingLabel, "GamePad Settings");
    lv_obj_set_style_text_color(ui_GamePadSettingLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GamePadSettingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GamePadSettingLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GameModeSettingStatePanel = lv_obj_create(ui_GamePadAppSettingScreen);
    lv_obj_set_width(ui_GameModeSettingStatePanel, 320);
    lv_obj_set_height(ui_GameModeSettingStatePanel, 25);
    lv_obj_clear_flag(ui_GameModeSettingStatePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GameModeSettingStatePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GameModeSettingStatePanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GameModeSettingStatePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GameModeSettingStatePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GameModeSettingStatePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GameModeSettingStatePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_GameModeSettingStatePanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel3 = lv_label_create(ui_GameModeSettingStatePanel);
    lv_obj_set_width(ui_TimeLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TimeLabel3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TimeLabel3, "12 : 00");
    lv_obj_set_style_text_color(ui_TimeLabel3, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeLabel3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bluetoothImage3 = lv_img_create(ui_GameModeSettingStatePanel);
    lv_img_set_src(ui_bluetoothImage3, &ui_img_ble_icon_20px_png);
    lv_obj_set_width(ui_bluetoothImage3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bluetoothImage3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bluetoothImage3, -106);
    lv_obj_set_y(ui_bluetoothImage3, 0);
    lv_obj_set_align(ui_bluetoothImage3, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_bluetoothImage3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bluetoothImage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiImage3 = lv_img_create(ui_GameModeSettingStatePanel);
    lv_img_set_src(ui_WifiImage3, &ui_img_wifi_icon_18px_png);
    lv_obj_set_width(ui_WifiImage3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiImage3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiImage3, -86);
    lv_obj_set_y(ui_WifiImage3, 0);
    lv_obj_set_align(ui_WifiImage3, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_WifiImage3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiImage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_usbImage3 = lv_img_create(ui_GameModeSettingStatePanel);
    lv_img_set_src(ui_usbImage3, &ui_img_usb_icon_20px_png);
    lv_obj_set_width(ui_usbImage3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_usbImage3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_usbImage3, -63);
    lv_obj_set_y(ui_usbImage3, 0);
    lv_obj_set_align(ui_usbImage3, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_usbImage3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_usbImage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_powerBar3 = lv_bar_create(ui_GameModeSettingStatePanel);
    lv_bar_set_value(ui_powerBar3, 60, LV_ANIM_OFF);
    lv_obj_set_width(ui_powerBar3, 30);
    lv_obj_set_height(ui_powerBar3, 13);
    lv_obj_set_x(ui_powerBar3, -28);
    lv_obj_set_y(ui_powerBar3, 0);
    lv_obj_set_align(ui_powerBar3, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_radius(ui_powerBar3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_powerBar3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_powerBar3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_powerBar3, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_powerBar3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_powerBar3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_powerBar3, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_powerBar3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_powerBar3, lv_color_hex(0x292929), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_powerBar3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_powerLab3 = lv_label_create(ui_GameModeSettingStatePanel);
    lv_obj_set_width(ui_powerLab3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powerLab3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_powerLab3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_powerLab3, "60%");
    lv_obj_set_style_text_color(ui_powerLab3, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_powerLab3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_powerLab3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_GameModeSettingStatePanel);
    lv_obj_set_width(ui_Panel5, 2);
    lv_obj_set_height(ui_Panel5, 5);
    lv_obj_set_x(ui_Panel5, -26);
    lv_obj_set_y(ui_Panel5, 0);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel5, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RockerCalibrationPanel = lv_obj_create(ui_GamePadAppSettingScreen);
    lv_obj_set_width(ui_RockerCalibrationPanel, 300);
    lv_obj_set_height(ui_RockerCalibrationPanel, 38);
    lv_obj_set_x(ui_RockerCalibrationPanel, 0);
    lv_obj_set_y(ui_RockerCalibrationPanel, 56);
    lv_obj_set_align(ui_RockerCalibrationPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RockerCalibrationPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RockerCalibrationPanel, 19, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RockerCalibrationPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RockerCalibrationPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RockerCalibrationPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RockerCalibrationPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RockerCalibrationPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_RockerCalibrationPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rockerCalibrationLab = lv_label_create(ui_RockerCalibrationPanel);
    lv_obj_set_width(ui_rockerCalibrationLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rockerCalibrationLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rockerCalibrationLab, -64);
    lv_obj_set_y(ui_rockerCalibrationLab, 0);
    lv_obj_set_align(ui_rockerCalibrationLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rockerCalibrationLab, "Rocker Calibration");
    lv_obj_set_style_text_font(ui_rockerCalibrationLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rockerCalibrationStartBtn = lv_btn_create(ui_RockerCalibrationPanel);
    lv_obj_set_width(ui_rockerCalibrationStartBtn, 100);
    lv_obj_set_height(ui_rockerCalibrationStartBtn, 30);
    lv_obj_set_x(ui_rockerCalibrationStartBtn, 95);
    lv_obj_set_y(ui_rockerCalibrationStartBtn, 0);
    lv_obj_set_align(ui_rockerCalibrationStartBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rockerCalibrationStartBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_rockerCalibrationStartBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rockerCalibrationStartBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rockerCalibrationStartBtn, lv_color_hex(0xF2A860), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rockerCalibrationStartBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_rockerCalibrationStartBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_rockerCalibrationStartBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_rockerCalibrationStartBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_rockerCalibrationStartBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_rockerCalibrationStartBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_rockerCalibrationStartBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rockerCalibrationStartBtnText = lv_label_create(ui_rockerCalibrationStartBtn);
    lv_obj_set_width(ui_rockerCalibrationStartBtnText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rockerCalibrationStartBtnText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rockerCalibrationStartBtnText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rockerCalibrationStartBtnText, "Start");
    lv_obj_set_style_text_color(ui_rockerCalibrationStartBtnText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rockerCalibrationStartBtnText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rockerCalibrationStartBtnText, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VibrationFeedbackPanel = lv_obj_create(ui_GamePadAppSettingScreen);
    lv_obj_set_width(ui_VibrationFeedbackPanel, 300);
    lv_obj_set_height(ui_VibrationFeedbackPanel, 38);
    lv_obj_set_x(ui_VibrationFeedbackPanel, 0);
    lv_obj_set_y(ui_VibrationFeedbackPanel, 8);
    lv_obj_set_align(ui_VibrationFeedbackPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_VibrationFeedbackPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_VibrationFeedbackPanel, 19, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VibrationFeedbackPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VibrationFeedbackPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_VibrationFeedbackPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VibrationFeedbackPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VibrationFeedbackPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_VibrationFeedbackPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VibrationFeedbackLab = lv_label_create(ui_VibrationFeedbackPanel);
    lv_obj_set_width(ui_VibrationFeedbackLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VibrationFeedbackLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VibrationFeedbackLab, -60);
    lv_obj_set_y(ui_VibrationFeedbackLab, 0);
    lv_obj_set_align(ui_VibrationFeedbackLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VibrationFeedbackLab, "Vibration Feedback");
    lv_obj_set_style_text_font(ui_VibrationFeedbackLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VibrationFeedbackBtn = lv_btn_create(ui_VibrationFeedbackPanel);
    lv_obj_set_width(ui_VibrationFeedbackBtn, 100);
    lv_obj_set_height(ui_VibrationFeedbackBtn, 30);
    lv_obj_set_x(ui_VibrationFeedbackBtn, 95);
    lv_obj_set_y(ui_VibrationFeedbackBtn, 0);
    lv_obj_set_align(ui_VibrationFeedbackBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VibrationFeedbackBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_VibrationFeedbackBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_VibrationFeedbackBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VibrationFeedbackBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VibrationFeedbackBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_VibrationFeedbackBtn, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VibrationFeedbackBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VibrationFeedbackBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_VibrationFeedbackBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_VibrationFeedbackBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_VibrationFeedbackBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_VibrationFeedbackBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_VibrationFeedbackBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_VibrationFeedbackBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_VibrationFeedbackBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VibrationFeedbackBtnPart = lv_btn_create(ui_VibrationFeedbackBtn);
    lv_obj_set_width(ui_VibrationFeedbackBtnPart, 48);
    lv_obj_set_height(ui_VibrationFeedbackBtnPart, 22);
    lv_obj_set_x(ui_VibrationFeedbackBtnPart, -22);
    lv_obj_set_y(ui_VibrationFeedbackBtnPart, 0);
    lv_obj_set_align(ui_VibrationFeedbackBtnPart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VibrationFeedbackBtnPart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_VibrationFeedbackBtnPart,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_VibrationFeedbackBtnPart, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VibrationFeedbackBtnPart, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VibrationFeedbackBtnPart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_VibrationFeedbackBtnPart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_VibrationFeedbackBtnPart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_VibrationFeedbackBtnPart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_VibrationFeedbackBtnPart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_VibrationFeedbackBtnPart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_VibrationFeedbackBtnPart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VibrationFeedbackStateLab = lv_label_create(ui_VibrationFeedbackBtnPart);
    lv_obj_set_width(ui_VibrationFeedbackStateLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VibrationFeedbackStateLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VibrationFeedbackStateLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VibrationFeedbackStateLab, "OFF");
    lv_obj_set_style_text_font(ui_VibrationFeedbackStateLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RockerCalibrationSettingPanel = lv_obj_create(ui_GamePadAppSettingScreen);
    lv_obj_set_width(ui_RockerCalibrationSettingPanel, 300);
    lv_obj_set_height(ui_RockerCalibrationSettingPanel, 100);
    lv_obj_set_x(ui_RockerCalibrationSettingPanel, 0);
    lv_obj_set_y(ui_RockerCalibrationSettingPanel, 59);
    lv_obj_set_align(ui_RockerCalibrationSettingPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RockerCalibrationSettingPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_RockerCalibrationSettingPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RockerCalibrationSettingPanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RockerCalibrationSettingPanel, lv_color_hex(0xF2A860), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RockerCalibrationSettingPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RockerCalibrationSettingPanel, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RockerCalibrationSettingPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RockerCalibrationSettingPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_RockerCalibrationSettingPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rockerCalibrationTipsLab = lv_label_create(ui_RockerCalibrationSettingPanel);
    lv_obj_set_width(ui_rockerCalibrationTipsLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rockerCalibrationTipsLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rockerCalibrationTipsLab, 0);
    lv_obj_set_y(ui_rockerCalibrationTipsLab, -35);
    lv_obj_set_align(ui_rockerCalibrationTipsLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rockerCalibrationTipsLab, "Release all rocker");
    lv_obj_set_style_text_color(ui_rockerCalibrationTipsLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rockerCalibrationTipsLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rockerCalibrationTipsLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftRockerCalibrate = lv_obj_create(ui_RockerCalibrationSettingPanel);
    lv_obj_set_width(ui_leftRockerCalibrate, 60);
    lv_obj_set_height(ui_leftRockerCalibrate, 60);
    lv_obj_set_x(ui_leftRockerCalibrate, -40);
    lv_obj_set_y(ui_leftRockerCalibrate, 15);
    lv_obj_set_align(ui_leftRockerCalibrate, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_leftRockerCalibrate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_leftRockerCalibrate, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_leftRockerCalibrate, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_leftRockerCalibrate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_leftRockerCalibrate, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftRockerCalibrateBtn = lv_btn_create(ui_leftRockerCalibrate);
    lv_obj_set_width(ui_leftRockerCalibrateBtn, 16);
    lv_obj_set_height(ui_leftRockerCalibrateBtn, 16);
    lv_obj_set_align(ui_leftRockerCalibrateBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_leftRockerCalibrateBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_leftRockerCalibrateBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_leftRockerCalibrateBtn, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_leftRockerCalibrateBtn, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_leftRockerCalibrateBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_leftRockerCalibrateBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_leftRockerCalibrateBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_leftRockerCalibrateBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_leftRockerCalibrateBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_leftRockerCalibrateBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_leftRockerCalibrateBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rightRockerCalibrate = lv_obj_create(ui_RockerCalibrationSettingPanel);
    lv_obj_set_width(ui_rightRockerCalibrate, 60);
    lv_obj_set_height(ui_rightRockerCalibrate, 60);
    lv_obj_set_x(ui_rightRockerCalibrate, 40);
    lv_obj_set_y(ui_rightRockerCalibrate, 15);
    lv_obj_set_align(ui_rightRockerCalibrate, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rightRockerCalibrate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rightRockerCalibrate, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rightRockerCalibrate, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rightRockerCalibrate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rightRockerCalibrate, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rightRockerCalibrateBtn = lv_btn_create(ui_rightRockerCalibrate);
    lv_obj_set_width(ui_rightRockerCalibrateBtn, 16);
    lv_obj_set_height(ui_rightRockerCalibrateBtn, 16);
    lv_obj_set_align(ui_rightRockerCalibrateBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rightRockerCalibrateBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_rightRockerCalibrateBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rightRockerCalibrateBtn, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rightRockerCalibrateBtn, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rightRockerCalibrateBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_rightRockerCalibrateBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_rightRockerCalibrateBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_rightRockerCalibrateBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_rightRockerCalibrateBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_rightRockerCalibrateBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_rightRockerCalibrateBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_hidModeSelectBtn, ui_event_hidModeSelectBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_gamePadSettingCloseBtn, ui_event_gamePadSettingCloseBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rockerCalibrationStartBtn, ui_event_rockerCalibrationStartBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VibrationFeedbackBtn, ui_event_VibrationFeedbackBtn, LV_EVENT_ALL, NULL);

}
