// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: BOX_REMOTE_CONTROL

#include "../ui.h"

void ui_GamePadAppScreen_screen_init(void)
{
    ui_GamePadAppScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GamePadAppScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GamePadAppScreen, lv_color_hex(0xFFF8E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GamePadAppScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GameTopPanel = lv_obj_create(ui_GamePadAppScreen);
    lv_obj_set_width(ui_GameTopPanel, 320);
    lv_obj_set_height(ui_GameTopPanel, 25);
    lv_obj_set_x(ui_GameTopPanel, 0);
    lv_obj_set_y(ui_GameTopPanel, -83);
    lv_obj_set_align(ui_GameTopPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GameTopPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GameTopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GameTopPanel, lv_color_hex(0xF2A860), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GameTopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GameTopPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GameTopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GameTopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_GameTopPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_returnBtnInGamePad = lv_btn_create(ui_GameTopPanel);
    lv_obj_set_width(ui_returnBtnInGamePad, 45);
    lv_obj_set_height(ui_returnBtnInGamePad, 20);
    lv_obj_set_x(ui_returnBtnInGamePad, -135);
    lv_obj_set_y(ui_returnBtnInGamePad, 0);
    lv_obj_set_align(ui_returnBtnInGamePad, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_returnBtnInGamePad, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_returnBtnInGamePad, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_returnBtnInGamePad, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_returnBtnInGamePad, lv_color_hex(0xF2A860), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_returnBtnInGamePad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_returnBtnInGamePad, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_returnBtnInGamePad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_returnBtnInGamePad, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_returnBtnInGamePad, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_returnBtnInGamePad, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_returnBtnInGamePad, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_returnBtnInGamePadIcon = lv_img_create(ui_returnBtnInGamePad);
    lv_img_set_src(ui_returnBtnInGamePadIcon, &ui_img_return_btn_16px_png);
    lv_obj_set_width(ui_returnBtnInGamePadIcon, 12);
    lv_obj_set_height(ui_returnBtnInGamePadIcon, 16);
    lv_obj_set_x(ui_returnBtnInGamePadIcon, -18);
    lv_obj_set_y(ui_returnBtnInGamePadIcon, 0);
    lv_obj_set_align(ui_returnBtnInGamePadIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_returnBtnInGamePadIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_returnBtnInGamePadIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_returnLabInGamePad = lv_label_create(ui_returnBtnInGamePad);
    lv_obj_set_width(ui_returnLabInGamePad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_returnLabInGamePad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_returnLabInGamePad, 5);
    lv_obj_set_y(ui_returnLabInGamePad, 0);
    lv_obj_set_align(ui_returnLabInGamePad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_returnLabInGamePad, "主页");
    lv_obj_set_style_text_color(ui_returnLabInGamePad, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_returnLabInGamePad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_returnLabInGamePad, &ui_font_SourceHanSansCN14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gameScreenTitle = lv_label_create(ui_GameTopPanel);
    lv_obj_set_width(ui_gameScreenTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gameScreenTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gameScreenTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gameScreenTitle, "GamePad");
    lv_obj_set_style_text_color(ui_gameScreenTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gameScreenTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gameScreenTitle, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GamePadTipsBtn = lv_btn_create(ui_GameTopPanel);
    lv_obj_set_width(ui_GamePadTipsBtn, 24);
    lv_obj_set_height(ui_GamePadTipsBtn, 24);
    lv_obj_set_x(ui_GamePadTipsBtn, 140);
    lv_obj_set_y(ui_GamePadTipsBtn, 0);
    lv_obj_set_align(ui_GamePadTipsBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GamePadTipsBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GamePadTipsBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GamePadTipsBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GamePadTipsBtn, lv_color_hex(0xF2A860), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GamePadTipsBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_GamePadTipsBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_GamePadTipsBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_GamePadTipsBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_GamePadTipsBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_GamePadTipsBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_GamePadTipsBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GamePadTipsBtnIcon = lv_img_create(ui_GamePadTipsBtn);
    lv_img_set_src(ui_GamePadTipsBtnIcon, &ui_img_setting_icon_20px_png);
    lv_obj_set_width(ui_GamePadTipsBtnIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GamePadTipsBtnIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GamePadTipsBtnIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GamePadTipsBtnIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_GamePadTipsBtnIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_upBtn = lv_btn_create(ui_GamePadAppScreen);
    lv_obj_set_width(ui_upBtn, 30);
    lv_obj_set_height(ui_upBtn, 30);
    lv_obj_set_x(ui_upBtn, -100);
    lv_obj_set_y(ui_upBtn, -4);
    lv_obj_set_align(ui_upBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_upBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_upBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_upBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_upBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_upBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_upBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_upBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_upBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_upBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_upBtn, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_upBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_upBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_upBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_upBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_upBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_upBtnIcon = lv_img_create(ui_upBtn);
    lv_img_set_src(ui_upBtnIcon, &ui_img_up_btn_png);
    lv_obj_set_width(ui_upBtnIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_upBtnIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_upBtnIcon, 0);
    lv_obj_set_y(ui_upBtnIcon, -1);
    lv_obj_set_align(ui_upBtnIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_upBtnIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_upBtnIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_leftBtn = lv_btn_create(ui_GamePadAppScreen);
    lv_obj_set_width(ui_leftBtn, 30);
    lv_obj_set_height(ui_leftBtn, 30);
    lv_obj_set_x(ui_leftBtn, -130);
    lv_obj_set_y(ui_leftBtn, 26);
    lv_obj_set_align(ui_leftBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_leftBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_leftBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_leftBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_leftBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_leftBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_leftBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_leftBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_leftBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_leftBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_leftBtn, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_leftBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_leftBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_leftBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_leftBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_leftBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftBtnIcon = lv_img_create(ui_leftBtn);
    lv_img_set_src(ui_leftBtnIcon, &ui_img_left_btn_png);
    lv_obj_set_width(ui_leftBtnIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_leftBtnIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_leftBtnIcon, -1);
    lv_obj_set_y(ui_leftBtnIcon, 0);
    lv_obj_set_align(ui_leftBtnIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_leftBtnIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_leftBtnIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rightBtn = lv_btn_create(ui_GamePadAppScreen);
    lv_obj_set_width(ui_rightBtn, 30);
    lv_obj_set_height(ui_rightBtn, 30);
    lv_obj_set_x(ui_rightBtn, -70);
    lv_obj_set_y(ui_rightBtn, 26);
    lv_obj_set_align(ui_rightBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rightBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_rightBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rightBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rightBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rightBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rightBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rightBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rightBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rightBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_rightBtn, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_rightBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_rightBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_rightBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_rightBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_rightBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rightBtnIcon = lv_img_create(ui_rightBtn);
    lv_img_set_src(ui_rightBtnIcon, &ui_img_right_btn_png);
    lv_obj_set_width(ui_rightBtnIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rightBtnIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rightBtnIcon, 1);
    lv_obj_set_y(ui_rightBtnIcon, 0);
    lv_obj_set_align(ui_rightBtnIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rightBtnIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_rightBtnIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_downBtn = lv_btn_create(ui_GamePadAppScreen);
    lv_obj_set_width(ui_downBtn, 30);
    lv_obj_set_height(ui_downBtn, 30);
    lv_obj_set_x(ui_downBtn, -100);
    lv_obj_set_y(ui_downBtn, 56);
    lv_obj_set_align(ui_downBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_downBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_downBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_downBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_downBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_downBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_downBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_downBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_downBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_downBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_downBtn, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_downBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_downBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_downBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_downBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_downBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_downBtnIcon = lv_img_create(ui_downBtn);
    lv_img_set_src(ui_downBtnIcon, &ui_img_down_btn_png);
    lv_obj_set_width(ui_downBtnIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_downBtnIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_downBtnIcon, 0);
    lv_obj_set_y(ui_downBtnIcon, 1);
    lv_obj_set_align(ui_downBtnIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_downBtnIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_downBtnIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yBtn = lv_btn_create(ui_GamePadAppScreen);
    lv_obj_set_width(ui_yBtn, 30);
    lv_obj_set_height(ui_yBtn, 30);
    lv_obj_set_x(ui_yBtn, 100);
    lv_obj_set_y(ui_yBtn, -4);
    lv_obj_set_align(ui_yBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_yBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_yBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_yBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_yBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_yBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_yBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_yBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_yBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_yBtn, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_yBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_yBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_yBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_yBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_yBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_xKeyLab = lv_label_create(ui_yBtn);
    lv_obj_set_width(ui_xKeyLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_xKeyLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_xKeyLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_xKeyLab, "Y");
    lv_obj_set_style_text_color(ui_xKeyLab, lv_color_hex(0xF2A860), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_xKeyLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_xKeyLab, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bBtn = lv_btn_create(ui_GamePadAppScreen);
    lv_obj_set_width(ui_bBtn, 30);
    lv_obj_set_height(ui_bBtn, 30);
    lv_obj_set_x(ui_bBtn, 130);
    lv_obj_set_y(ui_bBtn, 26);
    lv_obj_set_align(ui_bBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_bBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_bBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_bBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_bBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_bBtn, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_bBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_bBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_bBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_bBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_bBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bKeyLab = lv_label_create(ui_bBtn);
    lv_obj_set_width(ui_bKeyLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bKeyLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bKeyLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bKeyLab, "B");
    lv_obj_set_style_text_color(ui_bKeyLab, lv_color_hex(0xEC6459), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bKeyLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bKeyLab, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aBtn = lv_btn_create(ui_GamePadAppScreen);
    lv_obj_set_width(ui_aBtn, 30);
    lv_obj_set_height(ui_aBtn, 30);
    lv_obj_set_x(ui_aBtn, 100);
    lv_obj_set_y(ui_aBtn, 56);
    lv_obj_set_align(ui_aBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_aBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_aBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_aBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_aBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_aBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_aBtn, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_aBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_aBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_aBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_aBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_aBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aKeyLab = lv_label_create(ui_aBtn);
    lv_obj_set_width(ui_aKeyLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aKeyLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_aKeyLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aKeyLab, "A");
    lv_obj_set_style_text_color(ui_aKeyLab, lv_color_hex(0x5FCE83), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aKeyLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aKeyLab, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_xBtn = lv_btn_create(ui_GamePadAppScreen);
    lv_obj_set_width(ui_xBtn, 30);
    lv_obj_set_height(ui_xBtn, 30);
    lv_obj_set_x(ui_xBtn, 70);
    lv_obj_set_y(ui_xBtn, 26);
    lv_obj_set_align(ui_xBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_xBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_xBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_xBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_xBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_xBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_xBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_xBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_xBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_xBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_xBtn, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_xBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_xBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_xBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_xBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_xBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_yKeyLab = lv_label_create(ui_xBtn);
    lv_obj_set_width(ui_yKeyLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_yKeyLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_yKeyLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_yKeyLab, "X");
    lv_obj_set_style_text_color(ui_yKeyLab, lv_color_hex(0x60A2F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_yKeyLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_yKeyLab, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbBtn = lv_btn_create(ui_GamePadAppScreen);
    lv_obj_set_width(ui_lbBtn, 40);
    lv_obj_set_height(ui_lbBtn, 20);
    lv_obj_set_x(ui_lbBtn, -100);
    lv_obj_set_y(ui_lbBtn, -58);
    lv_obj_set_align(ui_lbBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lbBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_lbBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lbBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lbBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lbBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lbBtn, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lbBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lbBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lbBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_lbBtn, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_lbBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_lbBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_lbBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_lbBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_lbBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbBtnLab = lv_label_create(ui_lbBtn);
    lv_obj_set_width(ui_lbBtnLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbBtnLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbBtnLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbBtnLab, "LB");
    lv_obj_set_style_text_color(ui_lbBtnLab, lv_color_hex(0x38393A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbBtnLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbBtnLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ltBtn = lv_btn_create(ui_GamePadAppScreen);
    lv_obj_set_width(ui_ltBtn, 40);
    lv_obj_set_height(ui_ltBtn, 20);
    lv_obj_set_x(ui_ltBtn, -100);
    lv_obj_set_y(ui_ltBtn, -34);
    lv_obj_set_align(ui_ltBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ltBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ltBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ltBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ltBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ltBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ltBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ltBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ltBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ltBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ltBtn, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ltBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ltBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ltBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ltBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ltBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ltBtnLab = lv_label_create(ui_ltBtn);
    lv_obj_set_width(ui_ltBtnLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ltBtnLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ltBtnLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ltBtnLab, "LT");
    lv_obj_set_style_text_color(ui_ltBtnLab, lv_color_hex(0x38393A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ltBtnLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ltBtnLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rbBtn = lv_btn_create(ui_GamePadAppScreen);
    lv_obj_set_width(ui_rbBtn, 40);
    lv_obj_set_height(ui_rbBtn, 20);
    lv_obj_set_x(ui_rbBtn, 100);
    lv_obj_set_y(ui_rbBtn, -58);
    lv_obj_set_align(ui_rbBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rbBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_rbBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rbBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rbBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rbBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rbBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rbBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rbBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rbBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_rbBtn, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_rbBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_rbBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_rbBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_rbBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_rbBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rbBtnLab = lv_label_create(ui_rbBtn);
    lv_obj_set_width(ui_rbBtnLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rbBtnLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rbBtnLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rbBtnLab, "RB");
    lv_obj_set_style_text_color(ui_rbBtnLab, lv_color_hex(0x38393A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rbBtnLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rbBtnLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rtBtn = lv_btn_create(ui_GamePadAppScreen);
    lv_obj_set_width(ui_rtBtn, 40);
    lv_obj_set_height(ui_rtBtn, 20);
    lv_obj_set_x(ui_rtBtn, 100);
    lv_obj_set_y(ui_rtBtn, -34);
    lv_obj_set_align(ui_rtBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rtBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_rtBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rtBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rtBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rtBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rtBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rtBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rtBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rtBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_rtBtn, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_rtBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_rtBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_rtBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_rtBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_rtBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rtBtnLab = lv_label_create(ui_rtBtn);
    lv_obj_set_width(ui_rtBtnLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rtBtnLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rtBtnLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rtBtnLab, "RT");
    lv_obj_set_style_text_color(ui_rtBtnLab, lv_color_hex(0x38393A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rtBtnLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rtBtnLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftRocker = lv_obj_create(ui_GamePadAppScreen);
    lv_obj_set_width(ui_leftRocker, 74);
    lv_obj_set_height(ui_leftRocker, 74);
    lv_obj_set_x(ui_leftRocker, -40);
    lv_obj_set_y(ui_leftRocker, 80);
    lv_obj_set_align(ui_leftRocker, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_leftRocker, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_leftRocker, 37, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_leftRocker, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_leftRocker, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_leftRocker, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_leftRocker, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_leftRocker, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_leftRocker, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_leftRocker, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_leftRocker, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_leftRocker, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftRockerBtn = lv_btn_create(ui_leftRocker);
    lv_obj_set_width(ui_leftRockerBtn, 30);
    lv_obj_set_height(ui_leftRockerBtn, 30);
    lv_obj_set_align(ui_leftRockerBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_leftRockerBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_leftRockerBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_leftRockerBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_leftRockerBtn, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_leftRockerBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_leftRockerBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_leftRockerBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_leftRockerBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_leftRockerBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_leftRockerBtn, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_leftRockerBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_leftRockerBtn, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_leftRockerBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rightRocker = lv_obj_create(ui_GamePadAppScreen);
    lv_obj_set_width(ui_rightRocker, 74);
    lv_obj_set_height(ui_rightRocker, 74);
    lv_obj_set_x(ui_rightRocker, 40);
    lv_obj_set_y(ui_rightRocker, 80);
    lv_obj_set_align(ui_rightRocker, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rightRocker, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rightRocker, 37, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rightRocker, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rightRocker, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rightRocker, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_rightRocker, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_rightRocker, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_rightRocker, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_rightRocker, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_rightRocker, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_rightRocker, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rightRockerBtn = lv_btn_create(ui_rightRocker);
    lv_obj_set_width(ui_rightRockerBtn, 30);
    lv_obj_set_height(ui_rightRockerBtn, 30);
    lv_obj_set_align(ui_rightRockerBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rightRockerBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_rightRockerBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rightRockerBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rightRockerBtn, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rightRockerBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rightRockerBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rightRockerBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rightRockerBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rightRockerBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_rightRockerBtn, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_rightRockerBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_rightRockerBtn, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_rightRockerBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_rightRockerBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_rightRockerBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_selectBtn = lv_btn_create(ui_GamePadAppScreen);
    lv_obj_set_width(ui_selectBtn, 55);
    lv_obj_set_height(ui_selectBtn, 24);
    lv_obj_set_x(ui_selectBtn, -35);
    lv_obj_set_y(ui_selectBtn, -19);
    lv_obj_set_align(ui_selectBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_selectBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_selectBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_selectBtn, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_selectBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_selectBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_selectBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_selectBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_selectBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_selectBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_selectBtn, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_selectBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_selectBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_selectBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_selectBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_selectBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_selectBtnLab = lv_label_create(ui_selectBtn);
    lv_obj_set_width(ui_selectBtnLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_selectBtnLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_selectBtnLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_selectBtnLab, "BACK");
    lv_obj_set_style_text_color(ui_selectBtnLab, lv_color_hex(0x38393A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_selectBtnLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_selectBtnLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startBtn = lv_btn_create(ui_GamePadAppScreen);
    lv_obj_set_width(ui_startBtn, 55);
    lv_obj_set_height(ui_startBtn, 24);
    lv_obj_set_x(ui_startBtn, 35);
    lv_obj_set_y(ui_startBtn, -19);
    lv_obj_set_align(ui_startBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_startBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_startBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_startBtn, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_startBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_startBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_startBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_startBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_startBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_startBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_startBtn, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_startBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_startBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_startBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_startBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_startBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startBtnLab = lv_label_create(ui_startBtn);
    lv_obj_set_width(ui_startBtnLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_startBtnLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_startBtnLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_startBtnLab, "START");
    lv_obj_set_style_text_color(ui_startBtnLab, lv_color_hex(0x38393A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_startBtnLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_startBtnLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GamePadStatePanel = lv_obj_create(ui_GamePadAppScreen);
    lv_obj_set_width(ui_GamePadStatePanel, 320);
    lv_obj_set_height(ui_GamePadStatePanel, 25);
    lv_obj_clear_flag(ui_GamePadStatePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GamePadStatePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GamePadStatePanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GamePadStatePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GamePadStatePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GamePadStatePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GamePadStatePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_GamePadStatePanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel1 = lv_label_create(ui_GamePadStatePanel);
    lv_obj_set_width(ui_TimeLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TimeLabel1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TimeLabel1, "12 : 00");
    lv_obj_set_style_text_color(ui_TimeLabel1, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeLabel1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bluetoothImage1 = lv_img_create(ui_GamePadStatePanel);
    lv_img_set_src(ui_bluetoothImage1, &ui_img_ble_icon_20px_png);
    lv_obj_set_width(ui_bluetoothImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bluetoothImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bluetoothImage1, -106);
    lv_obj_set_y(ui_bluetoothImage1, 0);
    lv_obj_set_align(ui_bluetoothImage1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_bluetoothImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bluetoothImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiImage1 = lv_img_create(ui_GamePadStatePanel);
    lv_img_set_src(ui_WifiImage1, &ui_img_wifi_icon_18px_png);
    lv_obj_set_width(ui_WifiImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiImage1, -86);
    lv_obj_set_y(ui_WifiImage1, 0);
    lv_obj_set_align(ui_WifiImage1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_WifiImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_usbImage1 = lv_img_create(ui_GamePadStatePanel);
    lv_img_set_src(ui_usbImage1, &ui_img_usb_icon_20px_png);
    lv_obj_set_width(ui_usbImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_usbImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_usbImage1, -63);
    lv_obj_set_y(ui_usbImage1, 0);
    lv_obj_set_align(ui_usbImage1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_usbImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_usbImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_powerBar1 = lv_bar_create(ui_GamePadStatePanel);
    lv_bar_set_value(ui_powerBar1, 60, LV_ANIM_OFF);
    lv_obj_set_width(ui_powerBar1, 30);
    lv_obj_set_height(ui_powerBar1, 13);
    lv_obj_set_x(ui_powerBar1, -28);
    lv_obj_set_y(ui_powerBar1, 0);
    lv_obj_set_align(ui_powerBar1, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_radius(ui_powerBar1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_powerBar1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_powerBar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_powerBar1, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_powerBar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_powerBar1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_powerBar1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_powerBar1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_powerBar1, lv_color_hex(0x292929), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_powerBar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_powerLab1 = lv_label_create(ui_GamePadStatePanel);
    lv_obj_set_width(ui_powerLab1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powerLab1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_powerLab1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_powerLab1, "60%");
    lv_obj_set_style_text_color(ui_powerLab1, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_powerLab1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_powerLab1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_returnBtnInGamePad, ui_event_returnBtnInGamePad, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GamePadTipsBtn, ui_event_GamePadTipsBtn, LV_EVENT_ALL, NULL);

}
