// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: BOX_REMOTE_CONTROL

#include "../ui.h"

void ui_RcAppScreen_screen_init(void)
{
    ui_RcAppScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RcAppScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RcAppScreen, lv_color_hex(0xFFF8E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RcAppScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EspDroneStatePanel = lv_obj_create(ui_RcAppScreen);
    lv_obj_set_width(ui_EspDroneStatePanel, 320);
    lv_obj_set_height(ui_EspDroneStatePanel, 25);
    lv_obj_clear_flag(ui_EspDroneStatePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_EspDroneStatePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_EspDroneStatePanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EspDroneStatePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_EspDroneStatePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EspDroneStatePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_EspDroneStatePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_EspDroneStatePanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel2 = lv_label_create(ui_EspDroneStatePanel);
    lv_obj_set_width(ui_TimeLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TimeLabel2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TimeLabel2, "12 : 00");
    lv_obj_set_style_text_color(ui_TimeLabel2, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeLabel2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bluetoothImage2 = lv_img_create(ui_EspDroneStatePanel);
    lv_img_set_src(ui_bluetoothImage2, &ui_img_ble_icon_20px_png);
    lv_obj_set_width(ui_bluetoothImage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bluetoothImage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bluetoothImage2, -106);
    lv_obj_set_y(ui_bluetoothImage2, 0);
    lv_obj_set_align(ui_bluetoothImage2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_bluetoothImage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bluetoothImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiImage2 = lv_img_create(ui_EspDroneStatePanel);
    lv_img_set_src(ui_WifiImage2, &ui_img_wifi_icon_18px_png);
    lv_obj_set_width(ui_WifiImage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiImage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiImage2, -86);
    lv_obj_set_y(ui_WifiImage2, 0);
    lv_obj_set_align(ui_WifiImage2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_WifiImage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_usbImage2 = lv_img_create(ui_EspDroneStatePanel);
    lv_img_set_src(ui_usbImage2, &ui_img_usb_icon_20px_png);
    lv_obj_set_width(ui_usbImage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_usbImage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_usbImage2, -63);
    lv_obj_set_y(ui_usbImage2, 0);
    lv_obj_set_align(ui_usbImage2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_usbImage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_usbImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_powerBar2 = lv_bar_create(ui_EspDroneStatePanel);
    lv_bar_set_value(ui_powerBar2, 60, LV_ANIM_OFF);
    lv_obj_set_width(ui_powerBar2, 30);
    lv_obj_set_height(ui_powerBar2, 13);
    lv_obj_set_x(ui_powerBar2, -28);
    lv_obj_set_y(ui_powerBar2, 0);
    lv_obj_set_align(ui_powerBar2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_radius(ui_powerBar2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_powerBar2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_powerBar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_powerBar2, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_powerBar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_powerBar2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_powerBar2, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_powerBar2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_powerBar2, lv_color_hex(0x292929), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_powerBar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_powerLab2 = lv_label_create(ui_EspDroneStatePanel);
    lv_obj_set_width(ui_powerLab2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powerLab2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_powerLab2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_powerLab2, "60%");
    lv_obj_set_style_text_color(ui_powerLab2, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_powerLab2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_powerLab2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_EspDroneStatePanel);
    lv_obj_set_width(ui_Panel3, 2);
    lv_obj_set_height(ui_Panel3, 5);
    lv_obj_set_x(ui_Panel3, -26);
    lv_obj_set_y(ui_Panel3, 0);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel3, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dLeftRockerPanel = lv_obj_create(ui_RcAppScreen);
    lv_obj_set_width(ui_dLeftRockerPanel, 100);
    lv_obj_set_height(ui_dLeftRockerPanel, 100);
    lv_obj_set_x(ui_dLeftRockerPanel, -75);
    lv_obj_set_y(ui_dLeftRockerPanel, 50);
    lv_obj_set_align(ui_dLeftRockerPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dLeftRockerPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dLeftRockerPanel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dLeftRockerPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dLeftRockerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dLeftRockerPanel, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dLeftRockerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dLeftRockerPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_dLeftRockerPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_dLeftRockerPanel, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_dLeftRockerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_dLeftRockerPanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_dLeftRockerPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dLeftRockerBtn = lv_btn_create(ui_dLeftRockerPanel);
    lv_obj_set_width(ui_dLeftRockerBtn, 40);
    lv_obj_set_height(ui_dLeftRockerBtn, 40);
    lv_obj_set_align(ui_dLeftRockerBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dLeftRockerBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dLeftRockerBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dLeftRockerBtn, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dLeftRockerBtn, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dLeftRockerBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_dLeftRockerBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_dLeftRockerBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_dLeftRockerBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_dLeftRockerBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_dLeftRockerBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_dLeftRockerBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dRightRockerPanel = lv_obj_create(ui_RcAppScreen);
    lv_obj_set_width(ui_dRightRockerPanel, 100);
    lv_obj_set_height(ui_dRightRockerPanel, 100);
    lv_obj_set_x(ui_dRightRockerPanel, 75);
    lv_obj_set_y(ui_dRightRockerPanel, 50);
    lv_obj_set_align(ui_dRightRockerPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dRightRockerPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dRightRockerPanel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dRightRockerPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dRightRockerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dRightRockerPanel, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dRightRockerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dRightRockerPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_dRightRockerPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_dRightRockerPanel, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_dRightRockerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_dRightRockerPanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_dRightRockerPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dRightRockerBtn = lv_btn_create(ui_dRightRockerPanel);
    lv_obj_set_width(ui_dRightRockerBtn, 40);
    lv_obj_set_height(ui_dRightRockerBtn, 40);
    lv_obj_set_align(ui_dRightRockerBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dRightRockerBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dRightRockerBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dRightRockerBtn, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dRightRockerBtn, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dRightRockerBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_dRightRockerBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_dRightRockerBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_dRightRockerBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_dRightRockerBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_dRightRockerBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_dRightRockerBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bindBtn = lv_btn_create(ui_RcAppScreen);
    lv_obj_set_width(ui_bindBtn, 40);
    lv_obj_set_height(ui_bindBtn, 40);
    lv_obj_set_x(ui_bindBtn, 0);
    lv_obj_set_y(ui_bindBtn, 5);
    lv_obj_set_align(ui_bindBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bindBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_bindBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_bindBtn, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bindBtn, lv_color_hex(0x00FF7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bindBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_bindBtn, &ui_img_espnow_bind_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bindBtn, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bindBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_bindBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_bindBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_bindBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_bindBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_bindBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_bindBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_bindBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RcTopPanel = lv_obj_create(ui_RcAppScreen);
    lv_obj_set_width(ui_RcTopPanel, 320);
    lv_obj_set_height(ui_RcTopPanel, 25);
    lv_obj_set_x(ui_RcTopPanel, 0);
    lv_obj_set_y(ui_RcTopPanel, -83);
    lv_obj_set_align(ui_RcTopPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RcTopPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RcTopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RcTopPanel, lv_color_hex(0x9AFF9A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RcTopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RcTopPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RcTopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RcTopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_RcTopPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_returnBtnInEspDrone = lv_btn_create(ui_RcTopPanel);
    lv_obj_set_width(ui_returnBtnInEspDrone, 45);
    lv_obj_set_height(ui_returnBtnInEspDrone, 20);
    lv_obj_set_x(ui_returnBtnInEspDrone, -130);
    lv_obj_set_y(ui_returnBtnInEspDrone, 0);
    lv_obj_set_align(ui_returnBtnInEspDrone, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_returnBtnInEspDrone, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_returnBtnInEspDrone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_returnBtnInEspDrone, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_returnBtnInEspDrone, lv_color_hex(0x9AFF9A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_returnBtnInEspDrone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_returnBtnInEspDrone, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_returnBtnInEspDrone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_returnBtnInEspDrone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_returnBtnInEspDrone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_returnBtnInEspDrone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_returnBtnInEspDrone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_returnBtnInEspDroneIcon = lv_img_create(ui_returnBtnInEspDrone);
    lv_img_set_src(ui_returnBtnInEspDroneIcon, &ui_img_return_btn_16px_png);
    lv_obj_set_width(ui_returnBtnInEspDroneIcon, 12);
    lv_obj_set_height(ui_returnBtnInEspDroneIcon, 16);
    lv_obj_set_x(ui_returnBtnInEspDroneIcon, -18);
    lv_obj_set_y(ui_returnBtnInEspDroneIcon, 0);
    lv_obj_set_align(ui_returnBtnInEspDroneIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_returnBtnInEspDroneIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_returnBtnInEspDroneIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_returnLabInEspDrone = lv_label_create(ui_returnBtnInEspDrone);
    lv_obj_set_width(ui_returnLabInEspDrone, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_returnLabInEspDrone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_returnLabInEspDrone, 5);
    lv_obj_set_y(ui_returnLabInEspDrone, 0);
    lv_obj_set_align(ui_returnLabInEspDrone, LV_ALIGN_CENTER);
    lv_label_set_text(ui_returnLabInEspDrone, "主页");
    lv_obj_set_style_text_color(ui_returnLabInEspDrone, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_returnLabInEspDrone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_returnLabInEspDrone, &ui_font_SourceHanSansCN14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_espDroneTitle = lv_label_create(ui_RcTopPanel);
    lv_obj_set_width(ui_espDroneTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_espDroneTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_espDroneTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_espDroneTitle, "Remote Controller");
    lv_obj_set_style_text_color(ui_espDroneTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_espDroneTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_espDroneTitle, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RcDataPanel = lv_obj_create(ui_RcAppScreen);
    lv_obj_set_width(ui_RcDataPanel, 220);
    lv_obj_set_height(ui_RcDataPanel, 40);
    lv_obj_set_x(ui_RcDataPanel, 0);
    lv_obj_set_y(ui_RcDataPanel, -40);
    lv_obj_set_align(ui_RcDataPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RcDataPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RcDataPanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RcDataPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RcDataPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RcDataPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RcDataPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RcDataPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_RcDataPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_RcDataPanel, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_RcDataPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RcDataPanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RcDataPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dPLabel = lv_label_create(ui_RcDataPanel);
    lv_obj_set_width(ui_dPLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dPLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dPLabel, -90);
    lv_obj_set_y(ui_dPLabel, 0);
    lv_obj_set_align(ui_dPLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dPLabel, "P:");
    lv_obj_set_style_text_color(ui_dPLabel, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dPLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dPLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dRLabel = lv_label_create(ui_RcDataPanel);
    lv_obj_set_width(ui_dRLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dRLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dRLabel, -40);
    lv_obj_set_y(ui_dRLabel, 0);
    lv_obj_set_align(ui_dRLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dRLabel, "R:");
    lv_obj_set_style_text_color(ui_dRLabel, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dRLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dRLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dTLabel = lv_label_create(ui_RcDataPanel);
    lv_obj_set_width(ui_dTLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dTLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dTLabel, 12);
    lv_obj_set_y(ui_dTLabel, 0);
    lv_obj_set_align(ui_dTLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dTLabel, "T:");
    lv_obj_set_style_text_color(ui_dTLabel, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dTLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dTLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dYLabel = lv_label_create(ui_RcDataPanel);
    lv_obj_set_width(ui_dYLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dYLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dYLabel, 69);
    lv_obj_set_y(ui_dYLabel, 0);
    lv_obj_set_align(ui_dYLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dYLabel, "Y:");
    lv_obj_set_style_text_color(ui_dYLabel, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dYLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dYLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dPLabelData = lv_label_create(ui_RcDataPanel);
    lv_obj_set_width(ui_dPLabelData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dPLabelData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dPLabelData, -70);
    lv_obj_set_y(ui_dPLabelData, 0);
    lv_obj_set_align(ui_dPLabelData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dPLabelData, "0");
    lv_obj_set_style_text_color(ui_dPLabelData, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dPLabelData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dPLabelData, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dRLabelData = lv_label_create(ui_RcDataPanel);
    lv_obj_set_width(ui_dRLabelData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dRLabelData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dRLabelData, -20);
    lv_obj_set_y(ui_dRLabelData, 0);
    lv_obj_set_align(ui_dRLabelData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dRLabelData, "0");
    lv_obj_set_style_text_color(ui_dRLabelData, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dRLabelData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dRLabelData, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dTLabelData = lv_label_create(ui_RcDataPanel);
    lv_obj_set_width(ui_dTLabelData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dTLabelData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dTLabelData, 39);
    lv_obj_set_y(ui_dTLabelData, 0);
    lv_obj_set_align(ui_dTLabelData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dTLabelData, "0%");
    lv_obj_set_style_text_color(ui_dTLabelData, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dTLabelData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dTLabelData, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dYLabelData = lv_label_create(ui_RcDataPanel);
    lv_obj_set_width(ui_dYLabelData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dYLabelData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dYLabelData, 89);
    lv_obj_set_y(ui_dYLabelData, 0);
    lv_obj_set_align(ui_dYLabelData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dYLabelData, "0");
    lv_obj_set_style_text_color(ui_dYLabelData, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dYLabelData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dYLabelData, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_bindBtn, ui_event_bindBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_returnBtnInEspDrone, ui_event_returnBtnInEspDrone, LV_EVENT_ALL, NULL);

}
